insert into users (username, email, bio, startDate, reputation) values ('ldoog0', 'wivy0@irs.gov', 'Corrosion of second degree of unsp toe(s) (nail), init', '2022-08-26 15:22:50', 0);
insert into users (username, email, bio, startDate, reputation) values ('afitchew1', 'edearlove1@hugedomains.com', 'Traum rupture of ligmt of l little finger at MCP/IP jt, init', '2021-10-19 04:24:53', 0);
insert into users (username, email, bio, startDate, reputation) values ('lmaddock2', 'omcnerlin2@livejournal.com', 'Other specified joint disorders, unspecified hand', '2021-11-01 11:09:32', 0);
insert into users (username, email, bio, startDate, reputation) values ('bcrew3', 'gdore3@wikispaces.com', 'Delayed puberty', '2021-11-08 00:33:03', 0);
insert into users (username, email, bio, startDate, reputation) values ('cbellfield4', 'sgurko4@telegraph.co.uk', 'Retained placenta without hemorrhage', '2022-07-23 18:39:19', 0);
insert into users (username, email, bio, startDate, reputation) values ('bstileman5', 'rcamois5@baidu.com', 'Hirsutism', '2022-01-05 11:05:17', 0);
insert into users (username, email, bio, startDate, reputation) values ('rdubarry6', 'akief6@ow.ly', 'Other infantile and juvenile cataract', '2022-05-25 07:50:52', 0);
insert into users (username, email, bio, startDate, reputation) values ('mlister7', 'wcotterell7@yahoo.co.jp', 'Person outside bus injured in clsn w pedl cyc in traf, subs', '2022-05-30 18:30:53', 0);
insert into users (username, email, bio, startDate, reputation) values ('gwellstead8', 'alocke8@google.co.uk', 'Amebic nondysenteric colitis', '2022-02-06 00:49:45', 0);
insert into users (username, email, bio, startDate, reputation) values ('bmccully9', 'acanelas9@discuz.net', 'Other displaced fracture of lower end of unspecified humerus', '2022-04-21 02:44:02', 0);
insert into users (username, email, bio, startDate, reputation) values ('bsassera', 'cbernakiewicza@artisteer.com', 'Congenital posterior urethral valves', '2022-02-23 13:20:03', 0);
insert into users (username, email, bio, startDate, reputation) values ('dgirodiasb', 'pwatfordb@wordpress.org', 'Fx unsp tarsal bone(s) of unsp ft, subs for fx w routn heal', '2022-06-12 04:12:18', 0);
insert into users (username, email, bio, startDate, reputation) values ('astenningsc', 'asimanekc@wp.com', 'Puncture wound with foreign body of anus, initial encounter', '2022-01-29 22:22:25', 0);
insert into users (username, email, bio, startDate, reputation) values ('epanyerd', 'nemanuellid@huffingtonpost.com', 'ABO incompatibility w delayed hemolytic transfs react, subs', '2021-11-01 17:45:40', 0);
insert into users (username, email, bio, startDate, reputation) values ('acovielloe', 'bvanhesterene@networksolutions.com', 'Contact with other specified machinery, subsequent encounter', '2021-12-22 11:12:57', 0);
insert into users (username, email, bio, startDate, reputation) values ('rdoddemeedef', 'mwinningf@washingtonpost.com', 'Sprain of unspecified cruciate ligament of knee', '2022-07-12 03:46:12', 0);
insert into users (username, email, bio, startDate, reputation) values ('barong', 'efakeg@hao123.com', 'Subluxation of radiocarpal joint of unspecified wrist', '2021-10-18 11:10:06', 0);
insert into users (username, email, bio, startDate, reputation) values ('pshaperoh', 'rgierckh@smh.com.au', 'Insect bite (nonvenomous), unspecified foot, sequela', '2022-05-30 10:58:53', 0);
insert into users (username, email, bio, startDate, reputation) values ('tlenini', 'gskiltoni@weather.com', 'Oth aplastic anemias and other bone marrow failure syndromes', '2021-12-06 13:02:34', 0);
insert into users (username, email, bio, startDate, reputation) values ('ptaylderj', 'apiotrj@paginegialle.it', 'Hypoplasia of penis', '2021-12-18 18:53:53', 0);
insert into users (username, email, bio, startDate, reputation) values ('jhawardk', 'dmazink@1und1.de', 'Ulcerative colitis, unspecified with other complication', '2021-12-18 18:06:40', 0);
insert into users (username, email, bio, startDate, reputation) values ('cwapplel', 'smcgladel@shinystat.com', 'Corrosion of unspecified degree of upper back, sequela', '2022-02-12 00:48:55', 0);
insert into users (username, email, bio, startDate, reputation) values ('llarkm', 'ycalamm@reverbnation.com', 'Toxic effect of noxious substances eaten as food, assault', '2022-02-08 22:09:04', 0);
insert into users (username, email, bio, startDate, reputation) values ('fhendrichsn', 'dickovitzn@washington.edu', 'Struck by falling object on other unpowered watercraft', '2022-03-30 01:51:11', 0);
insert into users (username, email, bio, startDate, reputation) values ('csimonazzio', 'bcalendaro@shinystat.com', 'Nondisp fx of greater tuberosity of l humer, 7thP', '2022-05-17 21:05:02', 0);
insert into users (username, email, bio, startDate, reputation) values ('vsommervillep', 'bmellingp@about.me', 'Posterior dislocation of unspecified hip', '2022-05-09 19:41:01', 0);
insert into users (username, email, bio, startDate, reputation) values ('leickhoffq', 'ccatleyq@live.com', 'Inj extn/abdr musc/fasc/tend of r thm at forarm lv, sequela', '2021-11-28 02:59:03', 0);
insert into users (username, email, bio, startDate, reputation) values ('icoughlinr', 'ascholefieldr@comsenz.com', 'Subluxation of interphalangeal joint of unsp lesser toe(s)', '2021-08-27 23:01:46', 0);
insert into users (username, email, bio, startDate, reputation) values ('otidgewells', 'cgregolins@google.co.uk', 'Unsp injury of deep palmar arch of left hand, subs encntr', '2021-10-01 04:46:18', 0);
insert into users (username, email, bio, startDate, reputation) values ('bhandst', 'akerleyt@nasa.gov', 'Driver of 3-whl mv injured in clsn w nonmtr vehicle in traf', '2022-02-16 08:00:18', 0);
insert into users (username, email, bio, startDate, reputation) values ('spelleru', 'lcholertonu@blogtalkradio.com', 'Insect bite (nonvenomous), unspecified foot, subs encntr', '2021-12-02 02:19:25', 0);
insert into users (username, email, bio, startDate, reputation) values ('awhitnellv', 'bvinkv@telegraph.co.uk', 'Disp fx of lateral malleolus of unsp fibula, 7thF', '2021-10-22 20:41:53', 0);
insert into users (username, email, bio, startDate, reputation) values ('thairsnapew', 'acheaterw@twitter.com', 'Other nonautoimmune hemolytic anemias', '2022-06-22 10:57:47', 0);
insert into users (username, email, bio, startDate, reputation) values ('sworrellx', 'ngrigoryevx@irs.gov', 'Poisoning by cocaine, undetermined', '2021-12-16 12:50:28', 0);
insert into users (username, email, bio, startDate, reputation) values ('ftregunnay', 'umcgeneayy@ox.ac.uk', 'Oth injuries of left wrist, hand and finger(s), sequela', '2022-07-02 19:24:52', 0);
insert into users (username, email, bio, startDate, reputation) values ('mdinningz', 'eshelleyz@joomla.org', 'Maternal care for chromosomal abnormality in fetus, fetus 1', '2022-04-21 23:24:16', 0);
insert into users (username, email, bio, startDate, reputation) values ('rseaborn10', 'osalkeld10@youtube.com', 'Unsp pedl cyclst inj in clsn w statnry object nontraf, sqla', '2021-10-11 21:47:18', 0);
insert into users (username, email, bio, startDate, reputation) values ('bvance11', 'aatterley11@behance.net', 'Oth psychoactive substance dependence w intoxication, unsp', '2022-04-01 15:03:39', 0);
insert into users (username, email, bio, startDate, reputation) values ('aspurr12', 'ggage12@hatena.ne.jp', 'Nondisplaced bimalleolar fracture of unsp lower leg, sequela', '2022-05-01 12:09:06', 0);
insert into users (username, email, bio, startDate, reputation) values ('adrewitt13', 'kszymanek13@adobe.com', 'Burn first degree of unsp single finger (nail) except thumb', '2021-12-23 10:24:32', 0);
insert into users (username, email, bio, startDate, reputation) values ('ctingly14', 'sheckle14@bandcamp.com', 'Displ spiral fx shaft of r femr, 7thM', '2021-10-16 08:34:35', 0);
insert into users (username, email, bio, startDate, reputation) values ('gshuttell15', 'bwrintmore15@constantcontact.com', 'Pedestrian on foot injured in collision w hv veh nontraf', '2022-03-04 23:40:35', 0);
insert into users (username, email, bio, startDate, reputation) values ('rpinkerton16', 'dprevett16@hexun.com', 'Path fracture in neoplastic disease, l shoulder, init', '2021-09-12 05:47:24', 0);
insert into users (username, email, bio, startDate, reputation) values ('jbussell17', 'edik17@shareasale.com', 'Suprvsn of preg with history of ectopic preg, second tri', '2022-07-16 10:22:55', 0);
insert into users (username, email, bio, startDate, reputation) values ('egonnard18', 'hconfort18@acquirethisname.com', 'Oth retrovirus as the cause of diseases classified elsewhere', '2022-05-16 22:14:05', 0);
insert into users (username, email, bio, startDate, reputation) values ('rfleckney19', 'iplom19@umn.edu', 'Retained (old) fb in iris or ciliary body, bilateral', '2021-09-06 01:55:23', 0);
insert into users (username, email, bio, startDate, reputation) values ('acrome1a', 'gfatscher1a@goo.ne.jp', 'Subluxation of proximal interphaln joint of l idx fngr, subs', '2021-11-12 14:29:53', 0);
insert into users (username, email, bio, startDate, reputation) values ('vhugh1b', 'kplaskitt1b@newyorker.com', 'Other secondary chronic gout, left elbow, with tophus', '2021-11-15 18:59:58', 0);
insert into users (username, email, bio, startDate, reputation) values ('gbaterip1c', 'vgrabert1c@acquirethisname.com', 'Other secondary osteonecrosis, unspecified shoulder', '2022-05-27 01:08:39', 0);
insert into users (username, email, bio, startDate, reputation) values ('wpembery1d', 'redy1d@cdc.gov', 'Sprain of the superior tibiofibul joint and ligament, l knee', '2022-03-26 12:56:27', 0);

insert into plant_types (type, commonName, fullName) values ('Vinyl', 'Showy Gilia', 'Gilia cana (M.E. Jones) A. Heller ssp. triceps (Brand) A.D. Grant & V.E. Grant');
insert into plant_types (type, commonName, fullName) values ('Vinyl', 'Hound''s Tongue', 'Cynoglossum L.');
insert into plant_types (type, commonName, fullName) values ('Glass', 'Graham''s Ticktrefoil', 'Desmodium grahamii A. Gray');
insert into plant_types (type, commonName, fullName) values ('Brass', 'Western Mountain Ash', 'Sorbus sitchensis M. Roem.');
insert into plant_types (type, commonName, fullName) values ('Wood', 'Calathea', 'Calathea G. Mey.');
insert into plant_types (type, commonName, fullName) values ('Rubber', 'Summer Farewell', 'Dalea pinnata (J.F. Gmel.) Barneby');
insert into plant_types (type, commonName, fullName) values ('Rubber', 'Cascara Buckthorn', 'Frangula purshiana (DC.) A. Gray');
insert into plant_types (type, commonName, fullName) values ('Glass', 'Erect Seaberry', 'Haloragis erecta (Murray) Eichler');
insert into plant_types (type, commonName, fullName) values ('Plastic', 'Jones'' Lupine', 'Lupinus jonesii Rydb.');
insert into plant_types (type, commonName, fullName) values ('Glass', 'Japanese Torreya', 'Torreya nucifera (L.) Siebold & Zucc.');
insert into plant_types (type, commonName, fullName) values ('Steel', 'Tortured Horsehair Lichen', 'Bryoria tortuosa (G. Merr.) Brodo & D. Hawksw.');
insert into plant_types (type, commonName, fullName) values ('Steel', 'Cyrto-hypnum Moss', 'Cyrto-hypnum involvens (Hedw.) W.R. Buck & H.A. Crum');
insert into plant_types (type, commonName, fullName) values ('Vinyl', 'Purplestem Aster', 'Symphyotrichum puniceum (L.) Á. Löve & D. Löve var. scabricaule (Shinners) G.L. Nesom');
insert into plant_types (type, commonName, fullName) values ('Granite', 'Fragile Leaf Dicranum Moss', 'Dicranum fragilifolium Lindb.');
insert into plant_types (type, commonName, fullName) values ('Brass', 'Raiche''s Clarkia', 'Clarkia concinna (Fisch. & C.A. Mey.) Greene ssp. raichei G. Allen, V. Ford & L. Gottlieb');
insert into plant_types (type, commonName, fullName) values ('Steel', 'Remy''s Sandmat', 'Chamaesyce remyi (A. Gray ex Boiss.) Croizat & O. Deg. var. kauaiensis (O. Deg. & Sherff) O. Deg. & I. Deg.');
insert into plant_types (type, commonName, fullName) values ('Brass', 'Linearleaf Snapdragon', 'Misopates orontium (L.) Raf.');
insert into plant_types (type, commonName, fullName) values ('Plexiglass', 'Tundra Shootingstar', 'Dodecatheon austrofrigidum K.L. Chambers');
insert into plant_types (type, commonName, fullName) values ('Plexiglass', 'Rim Lichen', 'Lecanora orae-frigidae R. Sant.');
insert into plant_types (type, commonName, fullName) values ('Steel', 'Wright''s Cudweed', 'Pseudognaphalium canescens (DC.) W.A. Weber ssp. microcephalum (Nutt.) Kartesz');
insert into plant_types (type, commonName, fullName) values ('Aluminum', 'Rough Stoneseed', 'Lithospermum matamorense DC.');
insert into plant_types (type, commonName, fullName) values ('Brass', 'Tracy''s Beaksedge', 'Rhynchospora tracyi Britton');
insert into plant_types (type, commonName, fullName) values ('Stone', 'False Rue Anemone', 'Enemion Raf.');
insert into plant_types (type, commonName, fullName) values ('Steel', 'Urban''s Flatsedge', 'Cyperus urbanii Boeckeler');
insert into plant_types (type, commonName, fullName) values ('Wood', 'Limestone Milkvetch', 'Astragalus titanophilus Barneby');
insert into plant_types (type, commonName, fullName) values ('Vinyl', 'Tall Townsend Daisy', 'Townsendia eximia A. Gray');
insert into plant_types (type, commonName, fullName) values ('Stone', 'Resinous Maiden Fern', 'Thelypteris resinifera (Desv.) Proctor');
insert into plant_types (type, commonName, fullName) values ('Steel', 'Strict Primrose', 'Primula stricta Hornem.');
insert into plant_types (type, commonName, fullName) values ('Granite', 'White Dammar', 'Vateria indica L.');
insert into plant_types (type, commonName, fullName) values ('Vinyl', 'Spotted Beebalm', 'Monarda punctata L. ssp. punctata var. intermedia (E.M. McClint. & Epling) Waterf.');
insert into plant_types (type, commonName, fullName) values ('Steel', 'Stiff Star-grass', 'Hypoxis rigida Chapm.');
insert into plant_types (type, commonName, fullName) values ('Granite', 'Rusty Swordfern', 'Polystichum echinatum (J.F. Gmel.) C. Chr.');
insert into plant_types (type, commonName, fullName) values ('Steel', 'Hall''s Fissidens Moss', 'Fissidens hallii Austin');
insert into plant_types (type, commonName, fullName) values ('Brass', 'Neckeropsis Moss', 'Neckeropsis Reichardt');
insert into plant_types (type, commonName, fullName) values ('Plastic', 'Cacao', 'Theobroma cacao L.');
insert into plant_types (type, commonName, fullName) values ('Plastic', 'Langsdorf''s Lousewort', 'Pedicularis langsdorffii Fisch. ex Stev.');
insert into plant_types (type, commonName, fullName) values ('Steel', 'Acid-loving Sedge', 'Carex acidicola Naczi');
insert into plant_types (type, commonName, fullName) values ('Glass', 'Woodland Rush', 'Juncus subcaudatus (Engelm.) Coville & S.F. Blake');
insert into plant_types (type, commonName, fullName) values ('Wood', 'Parmotrema Lichen', 'Parmotrema xanthinum (Müll. Arg.) Hale');
insert into plant_types (type, commonName, fullName) values ('Stone', 'Western False Asphodel', 'Triantha occidentalis (S. Watson) Gates');
insert into plant_types (type, commonName, fullName) values ('Plastic', 'Virginia Strawberry', 'Fragaria virginiana Duchesne ssp. virginiana');
insert into plant_types (type, commonName, fullName) values ('Vinyl', 'Paradox Spilonema Lichen', 'Spilonema paradoxum Bornet');
insert into plant_types (type, commonName, fullName) values ('Plastic', 'Purple Coneflower', 'Echinacea Moench');
insert into plant_types (type, commonName, fullName) values ('Granite', 'Alsike Clover', 'Trifolium hybridum L.');
insert into plant_types (type, commonName, fullName) values ('Wood', 'Geysers Panicgrass', 'Dichanthelium acuminatum (Sw.) Gould & C.A. Clark var. thermale (Bol.) Freckmann');
insert into plant_types (type, commonName, fullName) values ('Steel', 'Sulphur-flower Buckwheat', 'Eriogonum umbellatum Torr. var. furcosum Reveal');
insert into plant_types (type, commonName, fullName) values ('Plexiglass', 'Golden Princesplume', 'Stanleya pinnata (Pursh) Britton var. integrifolia (James ex Torr.) Rollins');
insert into plant_types (type, commonName, fullName) values ('Stone', 'Fairyduster', 'Calliandra eriophylla Benth.');
insert into plant_types (type, commonName, fullName) values ('Rubber', 'Hairy Yellow Vetch', 'Vicia hybrida L.');
insert into plant_types (type, commonName, fullName) values ('Brass', 'Hamatocaulis Moss', 'Hamatocaulis vernicosus (Mitt.) Hedenäs');

insert into activity_types (name, activityDesc) values ('watering', 'You must water your plant regualrly');
insert into activity_types (name, activityDesc) values ('repotting', 'Is it time to re-pot your plant yet?');
INSERT INTO activity_types (name, activityDesc) VALUES ("fertilising", "Is it time to fertilise your plant?");

insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (1, 'jcb', 'Vietnam', 11, 22, 24);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (2, 'mastercard', 'Chile', 4, 17, 32);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (3, 'americanexpress', 'China', 8, 11, 17);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (4, 'jcb', 'Sweden', 9, 31, 33);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (5, 'americanexpress', 'Ukraine', 11, 11, 39);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (6, 'maestro', 'Philippines', 9, 28, 39);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (7, 'jcb', 'Bahamas', 9, 25, 28);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (8, 'instapayment', 'Ukraine', 7, 10, 10);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (9, 'bankcard', 'Indonesia', 10, null, null);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (10, 'jcb', 'South Africa', 6, 19, 37);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (11, 'jcb', 'China', 9, 10, 21);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (12, 'mastercard', 'Norway', 7, 14, 38);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (13, 'jcb', 'Indonesia', 11, 16, 27);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (14, 'bankcard', 'France', 7, 12, 17);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (15, 'jcb', 'Guatemala', 7, 26, 17);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (16, 'jcb', 'France', 3, 19, 30);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (17, 'maestro', 'China', 8, null, null);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (18, 'mastercard', 'Poland', 9, 19, 36);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (19, 'china-unionpay', 'Poland', 6, 36, 36);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (20, 'jcb', 'Israel', 9, 16, 28);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (21, 'instapayment', 'Philippines', 7, 36, 19);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (22, 'diners-club-enroute', 'Brazil', 11, null, null);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (23, 'americanexpress', 'Russia', 11, 17, 22);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (24, 'jcb', 'Indonesia', 10, 40, 34);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (25, 'jcb', 'Ecuador', 7, 33, 17);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (26, 'jcb', 'China', 3, null, null);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (27, 'china-unionpay', 'Sweden', 11, 32, 17);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (28, 'instapayment', 'France', 11, 24, 20);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (29, 'switch', 'Zimbabwe', 9, 32, 34);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (30, 'maestro', 'Albania', 7, 36, 39);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (31, 'mastercard', 'China', 5, null, null);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (32, 'china-unionpay', 'Egypt', 7, 12, 37);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (33, 'mastercard', 'South Africa', 11, 24, 30);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (34, 'mastercard', 'Pakistan', 3, null, null);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (35, 'switch', 'Sweden', 4, null, null);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (36, 'china-unionpay', 'Egypt', 10, 14, 35);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (37, 'jcb', 'Bolivia', 8, 40, 28);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (38, 'visa', 'France', 5, 13, 34);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (39, 'diners-club-enroute', 'China', 9, 33, 15);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (40, 'mastercard', 'China', 3, 20, 21);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (41, 'jcb', 'Indonesia', 7, 36, 29);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (42, 'diners-club-enroute', 'Brazil', 5, 28, 36);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (43, 'instapayment', 'France', 10, 16, 10);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (44, 'solo', 'Papua New Guinea', 11, null, null);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (45, 'switch', 'Georgia', 10, 36, 16);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (46, 'instapayment', 'Czech Republic', 6, 33, 21);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (47, 'china-unionpay', 'Iran', 5, 25, 32);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (48, 'diners-club-us-ca', 'Somalia', 3, 35, 17);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (49, 'jcb', 'Indonesia', 11, 28, 37);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (50, 'switch', 'Indonesia', 7, null, null);

insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Cupressaceae', 'Orange', 1, 73, 89);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Fagaceae', 'Pink', 89, 22, 57);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Polemoniaceae', 'Violet', 2, 74, 27);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Splachnobryaceae', 'Teal', 63, 52, 10);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Scrophulariaceae', 'Teal', 81, 27, 54);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Lecanoraceae', 'Goldenrod', 38, 92, 96);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Brassicaceae', 'Green', 45, 91, 26);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Poaceae', 'Red', 96, 6, 38);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Onagraceae', 'Violet', 71, 68, 40);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Poaceae', 'Orange', 62, 83, 54);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Scrophulariaceae', 'Violet', 44, 21, 33);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Viscaceae', 'Crimson', 93, 51, 55);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Rhizocarpaceae', 'Orange', 47, 82, null);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Portulacaceae', 'Fuscia', 24, 99, 60);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Cladoniaceae', 'Purple', 45, 15, 65);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Caryophyllaceae', 'Teal', 64, 84, 55);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Nyctaginaceae', 'Green', 60, 6, null);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Hydrophyllaceae', 'Fuscia', 14, 61, 12);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Lamiaceae', 'Yellow', 29, 78, 40);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Brassicaceae', 'Crimson', 63, 92, 68);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Boraginaceae', 'Puce', 20, 98, 20);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Arecaceae', 'Orange', 25, 60, 40);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Asteraceae', 'Crimson', 31, 76, 99);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Ericaceae', 'Turquoise', 65, null, null);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Cyperaceae', 'Puce', 88, 21, null);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Polygalaceae', 'Indigo', 94, 39, 55);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Cyperaceae', 'Aquamarine', 3, 16, 53);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Pinaceae', 'Turquoise', 34, 83, 20);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Poaceae', 'Mauv', 7, 55, 29);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Asteraceae', 'Red', 98, 17, 11);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Lecideaceae', 'Mauv', 99, 71, 93);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Poaceae', 'Orange', 73, 13, 19);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Apiaceae', 'Orange', 70, 20, 17);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Apiaceae', 'Khaki', 66, 100, 30);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Asteraceae', 'Purple', 37, 14, 38);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Rosaceae', 'Indigo', 11, 49, 54);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Polemoniaceae', 'Maroon', 78, 44, 49);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Rubiaceae', 'Teal', 99, 70, 31);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Rosaceae', 'Maroon', 38, 57, 58);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Asteraceae', 'Orange', 88, 66, null);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Asteraceae', 'Pink', 55, 37, 57);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Asteraceae', 'Green', 41, 11, 99);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Hymeneliaceae', 'Crimson', 70, 64, 3);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Scrophulariaceae', 'Purple', 15, 92, 89);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Cladoniaceae', 'Khaki', 83, 25, null);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Fagaceae', 'Red', 94, 99, 50);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Araucariaceae', 'Purple', 39, 30, 39);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Lecanoraceae', 'Violet', 10, 13, 91);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Scrophulariaceae', 'Goldenrod', 13, 56, 11);
insert into plant_care_profile (soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values ('Rosaceae', 'Yellow', 24, 6, 85);

insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Solanaceae', 'Flexidy', 4, 4, 9);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Ericaceae', 'Y-Solowarm', 8, 39, 11);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Lythraceae', 'Gembucket', 18, 28, 50);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Brassicaceae', 'Cardify', 15, 22, 20);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Juncaceae', 'Opela', 2, 14, 41);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Poaceae', 'Namfix', 1, 4, 10);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Liliaceae', 'Keylex', 31, 44, 17);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Polemoniaceae', 'Zamit', 10, 49, 27);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Gentianaceae', 'Overhold', 26, 5, 28);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Psoraceae', 'Tampflex', 12, 6, 33);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Salviniaceae', 'Trippledex', 41, 38, 32);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Asteraceae', 'Opela', 25, 48, 47);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Apiaceae', 'Domainer', 46, 33, 4);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Potamogetonaceae', 'Duobam', 41, 12, 2);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Ericaceae', 'Redhold', 29, 49, 16);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Teloschistaceae', 'Kanlam', 34, 41, 36);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Cactaceae', 'Sub-Ex', 1, 36, 25);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Iridaceae', 'Greenlam', 18, 3, 28);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Brassicaceae', 'Fintone', 47, 28, 23);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Strelitziaceae', 'Solarbreeze', 37, 40, 34);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Bombacaceae', 'Treeflex', 48, 42, 15);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Bartramiaceae', 'Andalax', 48, 44, 21);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Rutaceae', 'Mat Lam Tam', 12, 25, 22);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Placynthiaceae', 'Rank', 10, 42, 30);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Rubiaceae', 'Zathin', 46, 41, 47);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Fabaceae', 'Otcom', 39, 28, 22);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Polemoniaceae', 'Cardify', 21, 4, 23);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Cyperaceae', 'Transcof', 45, 27, 43);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Rubiaceae', 'Trippledex', 38, 17, 10);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Pteridaceae', 'Trippledex', 6, 46, 9);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Asteraceae', 'Cookley', 2, 41, 22);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Lycopodiaceae', 'Redhold', 45, 31, 36);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Juncaceae', 'Opela', 5, 44, 12);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Eigleraceae', 'Fixflex', 3, 45, 30);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Agavaceae', 'Asoka', 8, 13, 41);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Fagaceae', 'Overhold', 33, 1, 17);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Asteraceae', 'Namfix', 32, 11, 45);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Campanulaceae', 'Rank', 44, 48, 41);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Cyperaceae', 'Otcom', 9, 8, 33);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Cyperaceae', 'Toughjoyfax', 44, 29, 40);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Begoniaceae', 'Kanlam', 48, 18, 41);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Brassicaceae', 'Daltfresh', 46, 20, 44);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Rutaceae', 'Duobam', 40, 25, 44);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Rosaceae', 'Holdlamis', 42, 41, 31);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Parmeliaceae', 'Voyatouch', 22, 6, 27);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Onagraceae', 'Domainer', 13, 14, 17);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Asteraceae', 'Latlux', 27, 47, 33);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Dioscoreaceae', 'Domainer', 42, 34, 30);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Polygonaceae', 'Fixflex', 49, 33, 26);
insert into plants (plantName, plantDesc, plantTypeId, userId, careProfileId) values ('Onagraceae', 'Veribet', 8, 35, 30);

insert into activities (activityTime, activityTypeId, plantId) values ('2022-07-18', 1, 2);
insert into activities (activityTime, activityTypeId, plantId) values ('2022-07-19', 2, 3);
insert into activities (activityTime, activityTypeId, plantId) values ('2022-07-19', 2, 2);

insert into tags (label) values ('African snake (unidentified)');
insert into tags (label) values ('European beaver');
insert into tags (label) values ('Brown lemur');
insert into tags (label) values ('Alligator, american');
insert into tags (label) values ('Squirrel, nelson ground');
insert into tags (label) values ('Agile wallaby');
insert into tags (label) values ('South African hedgehog');
insert into tags (label) values ('Snow goose');
insert into tags (label) values ('Black-crowned crane');
insert into tags (label) values ('Rhinoceros, black');
insert into tags (label) values ('Madagascar hawk owl');
insert into tags (label) values ('Goose, snow');
insert into tags (label) values ('Cat, ringtail');
insert into tags (label) values ('Squirrel, nelson ground');
insert into tags (label) values ('Ibis, sacred');
insert into tags (label) values ('Striated heron');
insert into tags (label) values ('Hippopotamus');
insert into tags (label) values ('Weaver, sociable');
insert into tags (label) values ('Openbill stork');
insert into tags (label) values ('Gull, kelp');
insert into tags (label) values ('Dolphin, striped');
insert into tags (label) values ('Brush-tailed rat kangaroo');
insert into tags (label) values ('Bent-toed gecko');
insert into tags (label) values ('Spotted deer');
insert into tags (label) values ('Openbill stork');
insert into tags (label) values ('Klipspringer');
insert into tags (label) values ('Gull, southern black-backed');
insert into tags (label) values ('Langur, gray');
insert into tags (label) values ('Langur, common');
insert into tags (label) values ('Kangaroo, jungle');
insert into tags (label) values ('Denham''s bustard');
insert into tags (label) values ('Alligator, american');
insert into tags (label) values ('Squirrel glider');
insert into tags (label) values ('Red-billed hornbill');
insert into tags (label) values ('Beisa oryx');
insert into tags (label) values ('Meerkat, red');
insert into tags (label) values ('Kelp gull');
insert into tags (label) values ('Bontebok');
insert into tags (label) values ('Pale-throated three-toed sloth');
insert into tags (label) values ('Blue-footed booby');
insert into tags (label) values ('Brush-tailed bettong');
insert into tags (label) values ('Yellow mongoose');
insert into tags (label) values ('Boa, emerald green tree');
insert into tags (label) values ('Deer, barasingha');
insert into tags (label) values ('Tortoise, burmese black mountain');
insert into tags (label) values ('Parrot, hawk-headed');
insert into tags (label) values ('Black-winged stilt');
insert into tags (label) values ('Trumpeter, green-winged');
insert into tags (label) values ('Savannah deer (unidentified)');
insert into tags (label) values ('Painted stork');

insert into plant_tags (plantTypeId, tagId) values (14, 14);
insert into plant_tags (plantTypeId, tagId) values (10, 42);
insert into plant_tags (plantTypeId, tagId) values (18, 49);
insert into plant_tags (plantTypeId, tagId) values (3, 39);
insert into plant_tags (plantTypeId, tagId) values (37, 24);
insert into plant_tags (plantTypeId, tagId) values (46, 35);
insert into plant_tags (plantTypeId, tagId) values (21, 24);
insert into plant_tags (plantTypeId, tagId) values (38, 31);
insert into plant_tags (plantTypeId, tagId) values (17, 13);
insert into plant_tags (plantTypeId, tagId) values (12, 43);
insert into plant_tags (plantTypeId, tagId) values (36, 1);
insert into plant_tags (plantTypeId, tagId) values (43, 26);
insert into plant_tags (plantTypeId, tagId) values (37, 41);
insert into plant_tags (plantTypeId, tagId) values (47, 2);
insert into plant_tags (plantTypeId, tagId) values (47, 1);
insert into plant_tags (plantTypeId, tagId) values (37, 14);
insert into plant_tags (plantTypeId, tagId) values (49, 35);
insert into plant_tags (plantTypeId, tagId) values (1, 5);
insert into plant_tags (plantTypeId, tagId) values (36, 29);
insert into plant_tags (plantTypeId, tagId) values (2, 40);
insert into plant_tags (plantTypeId, tagId) values (5, 11);
insert into plant_tags (plantTypeId, tagId) values (34, 46);
insert into plant_tags (plantTypeId, tagId) values (32, 4);
insert into plant_tags (plantTypeId, tagId) values (16, 22);
insert into plant_tags (plantTypeId, tagId) values (2, 37);
insert into plant_tags (plantTypeId, tagId) values (14, 28);
insert into plant_tags (plantTypeId, tagId) values (46, 27);
insert into plant_tags (plantTypeId, tagId) values (44, 36);
insert into plant_tags (plantTypeId, tagId) values (27, 15);
insert into plant_tags (plantTypeId, tagId) values (45, 15);
insert into plant_tags (plantTypeId, tagId) values (40, 41);
insert into plant_tags (plantTypeId, tagId) values (17, 24);
insert into plant_tags (plantTypeId, tagId) values (36, 43);
insert into plant_tags (plantTypeId, tagId) values (40, 29);
insert into plant_tags (plantTypeId, tagId) values (5, 3);
insert into plant_tags (plantTypeId, tagId) values (14, 17);
insert into plant_tags (plantTypeId, tagId) values (15, 38);
insert into plant_tags (plantTypeId, tagId) values (23, 34);
insert into plant_tags (plantTypeId, tagId) values (23, 22);
insert into plant_tags (plantTypeId, tagId) values (28, 38);
insert into plant_tags (plantTypeId, tagId) values (23, 1);
insert into plant_tags (plantTypeId, tagId) values (48, 24);
insert into plant_tags (plantTypeId, tagId) values (4, 37);
insert into plant_tags (plantTypeId, tagId) values (39, 45);
insert into plant_tags (plantTypeId, tagId) values (37, 18);
insert into plant_tags (plantTypeId, tagId) values (11, 33);
insert into plant_tags (plantTypeId, tagId) values (32, 25);
insert into plant_tags (plantTypeId, tagId) values (34, 16);
insert into plant_tags (plantTypeId, tagId) values (24, 20);
insert into plant_tags (plantTypeId, tagId) values (48, 28);

/* Data for sample end user - sanitised data developed using app's test jsons */
insert into users (id, username, email, bio, startDate, reputation) values (666, 'bombsquad', 'ted@kaczynski.com', 'You got mail!', '2022-05-30 18:30:53', 0);

insert into plant_types (id, type, commonName, fullName) values (101, 'Succulent', 'Aloe Vera', 'Aloe vera');
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (101, 'mediumPot', 'fullSun', 37, 90, 90);
insert into plant_care_profile (id, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (101, 'mediumPot', 'fullSun', 37, 90, 90);
insert into plants (id, plantName, plantDesc, plantTypeId, userId, careProfileId) values (101, 'Mittens', 'My sweet beautiful son', 101, 666, 101);
insert into activities (activityTime, activityTypeId, plantId) values ('2022-08-18', 1, 101);
insert into activities (activityTime, activityTypeId, plantId) values ('2022-08-30', 1, 101);
insert into photos (uri, photoTime, plantId) values ("https://www.almanac.com/sites/default/files/styles/large/public/image_nodes/aloe-vera-white-pot_sunwand24-ss_edit.jpg?itok=6dE5RWDP", "2022-08-20T15:30", 101);

insert into plant_types (id, type, commonName, fullName) values (102, 'Monstera', 'Common Monstera', 'Monstera deliciosa');
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (102, 'mediumPot', 'fullShade', 7, 39, 60);
insert into plant_care_profile (id, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (102, 'mediumPot', 'fullShade', 7, 39, 60);
insert into plants (id, plantName, plantDesc, plantTypeId, userId, careProfileId) values (102, 'Teddy', "", 102, 666, 102);
insert into activities (activityTime, activityTypeId, plantId) values ('2022-08-18', 1, 102);
insert into activities (activityTime, activityTypeId, plantId) values ('2022-08-30', 1, 102);
insert into photos (uri, photoTime, plantId) values ("https://www.thespruce.com/thmb/Yn-yjMFQGSvoH4_r3y-mLljqrjY=/4461x3346/smart/filters:no_upscale()/grow-monstera-adansonii-swiss-cheese-plant-1902774-hero-01-dc903dae459a4dd5b919d5e1d1bee9d3.jpg", "2022-08-20T15:30", 102);
insert into photos (uri, photoTime, plantId) values ("https://cdn.shopify.com/s/files/1/0416/6438/1085/products/monstera_900x.jpg?v=1659019393", "2022-08-18T14:15", 102);

insert into plant_types (id, type, commonName, fullName) values (103, 'Chili', "Bird's Eye Chili", 'Capsicum Annuum');
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (103, 'mediumPot', 'partShade', 3, 40, 50);
insert into plant_care_profile (id, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (103, 'mediumPot', 'partShade', 3, 40, 50);
insert into plants (id, plantName, plantDesc, plantTypeId, userId, careProfileId) values (103, 'Spicy', 'hot hot boi', 103, 666, 103);
insert into activities (activityTime, activityTypeId, plantId) values ('2022-08-18', 1, 103);
insert into activities (activityTime, activityTypeId, plantId) values ('2022-08-30', 1, 103);
insert into photos (uri, photoTime, plantId) values ("https://www.bolster.eu/media/images/1635_dbweb.jpg?1549350221", "2022-08-20T15:30", 103);

insert into plant_types (id, type, commonName, fullName) values (104, 'Pothos', "House Pothos", 'Epipremnum Aureum');
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (104, 'fishTank', 'indoor', 10, 50, 70);
insert into plant_care_profile (id, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (104, 'fishTank', 'indoor', 10, 50, 70);
insert into plants (id, plantName, plantDesc, plantTypeId, userId, careProfileId) values (104, 'Caspar', 'Needs special care', 104, 666, 104);
insert into activities (activityTime, activityTypeId, plantId) values ('2022-08-18', 1, 104);
insert into activities (activityTime, activityTypeId, plantId) values ('2022-08-30', 1, 104);
insert into photos (uri, photoTime, plantId) values ("https://cdn.shopify.com/s/files/1/0046/2467/9000/products/original_4ef6c2c8-df24-40a5-a410-92ade77f3504_2400x.jpg?v=1653960466", "2022-08-20T15:30", 104);


/* Additional plant types taken from plantnet database */
insert into plant_types (id, type, commonName, fullName) values (201, 'Vegetable', 'Corn', 'Zea mays');
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (201, 'gardenBed', 'fullSun', 9, 40, 40);

insert into plant_types (id, type, commonName, fullName) values (202, 'Rose', 'Bengal rose', 'Rosa chinensis');
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (202, 'gardenBed', 'partShade', 5, 50, 15);

insert into plant_types (id, type, commonName, fullName) values (203, 'Evergreen', 'Snakeplant', 'Sansevieria trifasciata');
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (203, 'smallPot', 'fullShade', 12, 61, 78);

insert into plant_types (id, type, commonName, fullName) values (204, 'Herb', 'Wild garlic', 'Allium ursinum');
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (204, 'largePot', 'fullShade', 5, 80, 71);

insert into plant_types (id, type, commonName, fullName) values (205, 'Houseplant', 'ZZ plant', 'Zamioculcas zamiifolia');
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (205, 'smallPot', 'indoor', 14, 73, 90);

insert into plant_types (id, type, commonName, fullName) values (206, 'Lily', 'Peace lily', 'Spathiphyllum wallisii');
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (206, 'smallPot', 'indoor', 6, 80, 14);

insert into plant_types (id, type, commonName, fullName) values (207, 'Houseplant', 'Spider plant', 'Chlorophytum comosum');
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (207, 'smallPot', 'partShade', 4, 73, 21);

insert into plant_types (id, type, commonName, fullName) values (208, 'Lily', 'Flamingo-lily', 'Anthurium andraeanum');
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (208, 'mediumPot', 'partShade', 7, 80, 56);

/* second rendition of mocking data */
insert into users (id, username, email, bio, startDate, reputation) values (251, 'milesdavis', 'milesdavis@jazz.com', 'A kind of blue...', '2022-08-22 15:30:53', 10);
insert into users (id, username, email, bio, startDate, reputation) values (123, 'coolDude', 'dudethatscool@cool.net', 'look, I know im cool alright', '2022-07-15 12:30:53', 5);

insert into posts (id, title, content, created, score, userId) values (20, 'Help, why is my plant doing this?', 'Could someone please help me? This is a really weird plant behaviour...', '2022-11-14 18:20:23', 8, 666);

insert into post_plants (id, plantId, postId) values (1, 1, 20);
insert into post_plants (id, plantId, postId) values (2, 2, 20);

insert into tags (id, label) values (877, 'Unhealthy');
insert into tags (id, label) values (894, 'Spots');
insert into tags (id, label) values (838, 'Tropical');

insert into post_tags (id, postId, tagId) values (1, 20, 877);
insert into post_tags (id, postId, tagId) values (2, 20, 894);
insert into post_tags (id, postId, tagId) values (3, 20, 838);

/* comments to post */
insert into comments (id, content, created, parentId, userId, postId, score) values (1, 'Hmm, im not entirely sure. Thats weird!', '2022-11-15 08:20:10', null, 251, 20, 0);
insert into comments (id, content, created, parentId, userId, postId, score) values (2, 'You might need to move your plant into the shade. Especially in your climate.', '2022-11-15 22:40:53', null, 123, 20, 5);

/* replies to comments */
insert into comments (id, content, created, parentId, userId, postId, score) values (3, 'Thank you! This solved it!!', '2022-03-30 08:20:10', 2, 666, 20, 2);