insert into users (username, email, bio, startDate, reputation) values ('ldoog0', 'wivy0@irs.gov', 'Corrosion of second degree of unsp toe(s) (nail), init', '2022-08-26 15:22:50', 0);
insert into users (username, email, bio, startDate, reputation) values ('afitchew1', 'edearlove1@hugedomains.com', 'Traum rupture of ligmt of l little finger at MCP/IP jt, init', '2021-10-19 04:24:53', 0);
insert into users (username, email, bio, startDate, reputation) values ('lmaddock2', 'omcnerlin2@livejournal.com', 'Other specified joint disorders, unspecified hand', '2021-11-01 11:09:32', 0);
insert into users (username, email, bio, startDate, reputation) values ('bcrew3', 'gdore3@wikispaces.com', 'Delayed puberty', '2021-11-08 00:33:03', 0);
insert into users (username, email, bio, startDate, reputation) values ('cbellfield4', 'sgurko4@telegraph.co.uk', 'Retained placenta without hemorrhage', '2022-07-23 18:39:19', 0);
insert into users (username, email, bio, startDate, reputation) values ('bstileman5', 'rcamois5@baidu.com', 'Hirsutism', '2022-01-05 11:05:17', 0);
insert into users (username, email, bio, startDate, reputation) values ('rdubarry6', 'akief6@ow.ly', 'Other infantile and juvenile cataract', '2022-05-25 07:50:52', 0);
insert into users (username, email, bio, startDate, reputation) values ('mlister7', 'wcotterell7@yahoo.co.jp', 'Person outside bus injured in clsn w pedl cyc in traf, subs', '2022-05-30 18:30:53', 0);
insert into users (username, email, bio, startDate, reputation) values ('gwellstead8', 'alocke8@google.co.uk', 'Amebic nondysenteric colitis', '2022-02-06 00:49:45', 0);
insert into users (username, email, bio, startDate, reputation) values ('bmccully9', 'acanelas9@discuz.net', 'Other displaced fracture of lower end of unspecified humerus', '2022-04-21 02:44:02', 0);
insert into users (username, email, bio, startDate, reputation) values ('bsassera', 'cbernakiewicza@artisteer.com', 'Congenital posterior urethral valves', '2022-02-23 13:20:03', 0);
insert into users (username, email, bio, startDate, reputation) values ('dgirodiasb', 'pwatfordb@wordpress.org', 'Fx unsp tarsal bone(s) of unsp ft, subs for fx w routn heal', '2022-06-12 04:12:18', 0);
insert into users (username, email, bio, startDate, reputation) values ('astenningsc', 'asimanekc@wp.com', 'Puncture wound with foreign body of anus, initial encounter', '2022-01-29 22:22:25', 0);
insert into users (username, email, bio, startDate, reputation) values ('epanyerd', 'nemanuellid@huffingtonpost.com', 'ABO incompatibility w delayed hemolytic transfs react, subs', '2021-11-01 17:45:40', 0);
insert into users (username, email, bio, startDate, reputation) values ('acovielloe', 'bvanhesterene@networksolutions.com', 'Contact with other specified machinery, subsequent encounter', '2021-12-22 11:12:57', 0);
insert into users (username, email, bio, startDate, reputation) values ('rdoddemeedef', 'mwinningf@washingtonpost.com', 'Sprain of unspecified cruciate ligament of knee', '2022-07-12 03:46:12', 0);
insert into users (username, email, bio, startDate, reputation) values ('barong', 'efakeg@hao123.com', 'Subluxation of radiocarpal joint of unspecified wrist', '2021-10-18 11:10:06', 0);
insert into users (username, email, bio, startDate, reputation) values ('pshaperoh', 'rgierckh@smh.com.au', 'Insect bite (nonvenomous), unspecified foot, sequela', '2022-05-30 10:58:53', 0);
insert into users (username, email, bio, startDate, reputation) values ('tlenini', 'gskiltoni@weather.com', 'Oth aplastic anemias and other bone marrow failure syndromes', '2021-12-06 13:02:34', 0);
insert into users (username, email, bio, startDate, reputation) values ('ptaylderj', 'apiotrj@paginegialle.it', 'Hypoplasia of penis', '2021-12-18 18:53:53', 0);
insert into users (username, email, bio, startDate, reputation) values ('jhawardk', 'dmazink@1und1.de', 'Ulcerative colitis, unspecified with other complication', '2021-12-18 18:06:40', 0);
insert into users (username, email, bio, startDate, reputation) values ('cwapplel', 'smcgladel@shinystat.com', 'Corrosion of unspecified degree of upper back, sequela', '2022-02-12 00:48:55', 0);
insert into users (username, email, bio, startDate, reputation) values ('llarkm', 'ycalamm@reverbnation.com', 'Toxic effect of noxious substances eaten as food, assault', '2022-02-08 22:09:04', 0);
insert into users (username, email, bio, startDate, reputation) values ('fhendrichsn', 'dickovitzn@washington.edu', 'Struck by falling object on other unpowered watercraft', '2022-03-30 01:51:11', 0);
insert into users (username, email, bio, startDate, reputation) values ('csimonazzio', 'bcalendaro@shinystat.com', 'Nondisp fx of greater tuberosity of l humer, 7thP', '2022-05-17 21:05:02', 0);
insert into users (username, email, bio, startDate, reputation) values ('vsommervillep', 'bmellingp@about.me', 'Posterior dislocation of unspecified hip', '2022-05-09 19:41:01', 0);
insert into users (username, email, bio, startDate, reputation) values ('leickhoffq', 'ccatleyq@live.com', 'Inj extn/abdr musc/fasc/tend of r thm at forarm lv, sequela', '2021-11-28 02:59:03', 0);
insert into users (username, email, bio, startDate, reputation) values ('icoughlinr', 'ascholefieldr@comsenz.com', 'Subluxation of interphalangeal joint of unsp lesser toe(s)', '2021-08-27 23:01:46', 0);
insert into users (username, email, bio, startDate, reputation) values ('otidgewells', 'cgregolins@google.co.uk', 'Unsp injury of deep palmar arch of left hand, subs encntr', '2021-10-01 04:46:18', 0);
insert into users (username, email, bio, startDate, reputation) values ('bhandst', 'akerleyt@nasa.gov', 'Driver of 3-whl mv injured in clsn w nonmtr vehicle in traf', '2022-02-16 08:00:18', 0);
insert into users (username, email, bio, startDate, reputation) values ('spelleru', 'lcholertonu@blogtalkradio.com', 'Insect bite (nonvenomous), unspecified foot, subs encntr', '2021-12-02 02:19:25', 0);
insert into users (username, email, bio, startDate, reputation) values ('awhitnellv', 'bvinkv@telegraph.co.uk', 'Disp fx of lateral malleolus of unsp fibula, 7thF', '2021-10-22 20:41:53', 0);
insert into users (username, email, bio, startDate, reputation) values ('thairsnapew', 'acheaterw@twitter.com', 'Other nonautoimmune hemolytic anemias', '2022-06-22 10:57:47', 0);
insert into users (username, email, bio, startDate, reputation) values ('sworrellx', 'ngrigoryevx@irs.gov', 'Poisoning by cocaine, undetermined', '2021-12-16 12:50:28', 0);
insert into users (username, email, bio, startDate, reputation) values ('ftregunnay', 'umcgeneayy@ox.ac.uk', 'Oth injuries of left wrist, hand and finger(s), sequela', '2022-07-02 19:24:52', 0);
insert into users (username, email, bio, startDate, reputation) values ('mdinningz', 'eshelleyz@joomla.org', 'Maternal care for chromosomal abnormality in fetus, fetus 1', '2022-04-21 23:24:16', 0);
insert into users (username, email, bio, startDate, reputation) values ('rseaborn10', 'osalkeld10@youtube.com', 'Unsp pedl cyclst inj in clsn w statnry object nontraf, sqla', '2021-10-11 21:47:18', 0);
insert into users (username, email, bio, startDate, reputation) values ('bvance11', 'aatterley11@behance.net', 'Oth psychoactive substance dependence w intoxication, unsp', '2022-04-01 15:03:39', 0);
insert into users (username, email, bio, startDate, reputation) values ('aspurr12', 'ggage12@hatena.ne.jp', 'Nondisplaced bimalleolar fracture of unsp lower leg, sequela', '2022-05-01 12:09:06', 0);
insert into users (username, email, bio, startDate, reputation) values ('adrewitt13', 'kszymanek13@adobe.com', 'Burn first degree of unsp single finger (nail) except thumb', '2021-12-23 10:24:32', 0);
insert into users (username, email, bio, startDate, reputation) values ('ctingly14', 'sheckle14@bandcamp.com', 'Displ spiral fx shaft of r femr, 7thM', '2021-10-16 08:34:35', 0);
insert into users (username, email, bio, startDate, reputation) values ('gshuttell15', 'bwrintmore15@constantcontact.com', 'Pedestrian on foot injured in collision w hv veh nontraf', '2022-03-04 23:40:35', 0);
insert into users (username, email, bio, startDate, reputation) values ('rpinkerton16', 'dprevett16@hexun.com', 'Path fracture in neoplastic disease, l shoulder, init', '2021-09-12 05:47:24', 0);
insert into users (username, email, bio, startDate, reputation) values ('jbussell17', 'edik17@shareasale.com', 'Suprvsn of preg with history of ectopic preg, second tri', '2022-07-16 10:22:55', 0);
insert into users (username, email, bio, startDate, reputation) values ('egonnard18', 'hconfort18@acquirethisname.com', 'Oth retrovirus as the cause of diseases classified elsewhere', '2022-05-16 22:14:05', 0);
insert into users (username, email, bio, startDate, reputation) values ('rfleckney19', 'iplom19@umn.edu', 'Retained (old) fb in iris or ciliary body, bilateral', '2021-09-06 01:55:23', 0);
insert into users (username, email, bio, startDate, reputation) values ('acrome1a', 'gfatscher1a@goo.ne.jp', 'Subluxation of proximal interphaln joint of l idx fngr, subs', '2021-11-12 14:29:53', 0);
insert into users (username, email, bio, startDate, reputation) values ('vhugh1b', 'kplaskitt1b@newyorker.com', 'Other secondary chronic gout, left elbow, with tophus', '2021-11-15 18:59:58', 0);
insert into users (username, email, bio, startDate, reputation) values ('gbaterip1c', 'vgrabert1c@acquirethisname.com', 'Other secondary osteonecrosis, unspecified shoulder', '2022-05-27 01:08:39', 0);
insert into users (username, email, bio, startDate, reputation) values ('wpembery1d', 'redy1d@cdc.gov', 'Sprain of the superior tibiofibul joint and ligament, l knee', '2022-03-26 12:56:27', 0);

insert into plant_types (type, commonName, fullName) values ('Vinyl', 'Showy Gilia', 'Gilia cana (M.E. Jones) A. Heller ssp. triceps (Brand) A.D. Grant & V.E. Grant');
insert into plant_types (type, commonName, fullName) values ('Vinyl', 'Hound''s Tongue', 'Cynoglossum L.');
insert into plant_types (type, commonName, fullName) values ('Glass', 'Graham''s Ticktrefoil', 'Desmodium grahamii A. Gray');
insert into plant_types (type, commonName, fullName) values ('Brass', 'Western Mountain Ash', 'Sorbus sitchensis M. Roem.');
insert into plant_types (type, commonName, fullName) values ('Wood', 'Calathea', 'Calathea G. Mey.');
insert into plant_types (type, commonName, fullName) values ('Rubber', 'Summer Farewell', 'Dalea pinnata (J.F. Gmel.) Barneby');
insert into plant_types (type, commonName, fullName) values ('Rubber', 'Cascara Buckthorn', 'Frangula purshiana (DC.) A. Gray');
insert into plant_types (type, commonName, fullName) values ('Glass', 'Erect Seaberry', 'Haloragis erecta (Murray) Eichler');
insert into plant_types (type, commonName, fullName) values ('Plastic', 'Jones'' Lupine', 'Lupinus jonesii Rydb.');
insert into plant_types (type, commonName, fullName) values ('Glass', 'Japanese Torreya', 'Torreya nucifera (L.) Siebold & Zucc.');
insert into plant_types (type, commonName, fullName) values ('Steel', 'Tortured Horsehair Lichen', 'Bryoria tortuosa (G. Merr.) Brodo & D. Hawksw.');
insert into plant_types (type, commonName, fullName) values ('Steel', 'Cyrto-hypnum Moss', 'Cyrto-hypnum involvens (Hedw.) W.R. Buck & H.A. Crum');
insert into plant_types (type, commonName, fullName) values ('Vinyl', 'Purplestem Aster', 'Symphyotrichum puniceum (L.) Á. Löve & D. Löve var. scabricaule (Shinners) G.L. Nesom');
insert into plant_types (type, commonName, fullName) values ('Granite', 'Fragile Leaf Dicranum Moss', 'Dicranum fragilifolium Lindb.');
insert into plant_types (type, commonName, fullName) values ('Brass', 'Raiche''s Clarkia', 'Clarkia concinna (Fisch. & C.A. Mey.) Greene ssp. raichei G. Allen, V. Ford & L. Gottlieb');
insert into plant_types (type, commonName, fullName) values ('Steel', 'Remy''s Sandmat', 'Chamaesyce remyi (A. Gray ex Boiss.) Croizat & O. Deg. var. kauaiensis (O. Deg. & Sherff) O. Deg. & I. Deg.');
insert into plant_types (type, commonName, fullName) values ('Brass', 'Linearleaf Snapdragon', 'Misopates orontium (L.) Raf.');
insert into plant_types (type, commonName, fullName) values ('Plexiglass', 'Tundra Shootingstar', 'Dodecatheon austrofrigidum K.L. Chambers');
insert into plant_types (type, commonName, fullName) values ('Plexiglass', 'Rim Lichen', 'Lecanora orae-frigidae R. Sant.');
insert into plant_types (type, commonName, fullName) values ('Steel', 'Wright''s Cudweed', 'Pseudognaphalium canescens (DC.) W.A. Weber ssp. microcephalum (Nutt.) Kartesz');
insert into plant_types (type, commonName, fullName) values ('Aluminum', 'Rough Stoneseed', 'Lithospermum matamorense DC.');
insert into plant_types (type, commonName, fullName) values ('Brass', 'Tracy''s Beaksedge', 'Rhynchospora tracyi Britton');
insert into plant_types (type, commonName, fullName) values ('Stone', 'False Rue Anemone', 'Enemion Raf.');
insert into plant_types (type, commonName, fullName) values ('Steel', 'Urban''s Flatsedge', 'Cyperus urbanii Boeckeler');
insert into plant_types (type, commonName, fullName) values ('Wood', 'Limestone Milkvetch', 'Astragalus titanophilus Barneby');
insert into plant_types (type, commonName, fullName) values ('Vinyl', 'Tall Townsend Daisy', 'Townsendia eximia A. Gray');
insert into plant_types (type, commonName, fullName) values ('Stone', 'Resinous Maiden Fern', 'Thelypteris resinifera (Desv.) Proctor');
insert into plant_types (type, commonName, fullName) values ('Steel', 'Strict Primrose', 'Primula stricta Hornem.');
insert into plant_types (type, commonName, fullName) values ('Granite', 'White Dammar', 'Vateria indica L.');
insert into plant_types (type, commonName, fullName) values ('Vinyl', 'Spotted Beebalm', 'Monarda punctata L. ssp. punctata var. intermedia (E.M. McClint. & Epling) Waterf.');
insert into plant_types (type, commonName, fullName) values ('Steel', 'Stiff Star-grass', 'Hypoxis rigida Chapm.');
insert into plant_types (type, commonName, fullName) values ('Granite', 'Rusty Swordfern', 'Polystichum echinatum (J.F. Gmel.) C. Chr.');
insert into plant_types (type, commonName, fullName) values ('Steel', 'Hall''s Fissidens Moss', 'Fissidens hallii Austin');
insert into plant_types (type, commonName, fullName) values ('Brass', 'Neckeropsis Moss', 'Neckeropsis Reichardt');
insert into plant_types (type, commonName, fullName) values ('Plastic', 'Cacao', 'Theobroma cacao L.');
insert into plant_types (type, commonName, fullName) values ('Plastic', 'Langsdorf''s Lousewort', 'Pedicularis langsdorffii Fisch. ex Stev.');
insert into plant_types (type, commonName, fullName) values ('Steel', 'Acid-loving Sedge', 'Carex acidicola Naczi');
insert into plant_types (type, commonName, fullName) values ('Glass', 'Woodland Rush', 'Juncus subcaudatus (Engelm.) Coville & S.F. Blake');
insert into plant_types (type, commonName, fullName) values ('Wood', 'Parmotrema Lichen', 'Parmotrema xanthinum (Müll. Arg.) Hale');
insert into plant_types (type, commonName, fullName) values ('Stone', 'Western False Asphodel', 'Triantha occidentalis (S. Watson) Gates');
insert into plant_types (type, commonName, fullName) values ('Plastic', 'Virginia Strawberry', 'Fragaria virginiana Duchesne ssp. virginiana');
insert into plant_types (type, commonName, fullName) values ('Vinyl', 'Paradox Spilonema Lichen', 'Spilonema paradoxum Bornet');
insert into plant_types (type, commonName, fullName) values ('Plastic', 'Purple Coneflower', 'Echinacea Moench');
insert into plant_types (type, commonName, fullName) values ('Granite', 'Alsike Clover', 'Trifolium hybridum L.');
insert into plant_types (type, commonName, fullName) values ('Wood', 'Geysers Panicgrass', 'Dichanthelium acuminatum (Sw.) Gould & C.A. Clark var. thermale (Bol.) Freckmann');
insert into plant_types (type, commonName, fullName) values ('Steel', 'Sulphur-flower Buckwheat', 'Eriogonum umbellatum Torr. var. furcosum Reveal');
insert into plant_types (type, commonName, fullName) values ('Plexiglass', 'Golden Princesplume', 'Stanleya pinnata (Pursh) Britton var. integrifolia (James ex Torr.) Rollins');
insert into plant_types (type, commonName, fullName) values ('Stone', 'Fairyduster', 'Calliandra eriophylla Benth.');
insert into plant_types (type, commonName, fullName) values ('Rubber', 'Hairy Yellow Vetch', 'Vicia hybrida L.');
insert into plant_types (type, commonName, fullName) values ('Brass', 'Hamatocaulis Moss', 'Hamatocaulis vernicosus (Mitt.) Hedenäs');

insert into activity_types (name, activityDesc) values ('watering', 'You must water your plant regualrly');
insert into activity_types (name, activityDesc) values ('repotting', 'Is it time to re-pot your plant yet?');
INSERT INTO activity_types (name, activityDesc) VALUES ("fertilising", "Is it time to fertilise your plant?");

insert into activities (activityTime, activityTypeId, plantId) values ('2022-07-18', 1, 2);
insert into activities (activityTime, activityTypeId, plantId) values ('2022-07-19', 2, 3);
insert into activities (activityTime, activityTypeId, plantId) values ('2022-07-19', 2, 2);

insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (1, 'jcb', 'Vietnam', 11, 22, 24);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (2, 'mastercard', 'Chile', 4, 17, 32);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (3, 'americanexpress', 'China', 8, 11, 17);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (4, 'jcb', 'Sweden', 9, 31, 33);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (5, 'americanexpress', 'Ukraine', 11, 11, 39);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (6, 'maestro', 'Philippines', 9, 28, 39);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (7, 'jcb', 'Bahamas', 9, 25, 28);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (8, 'instapayment', 'Ukraine', 7, 10, 10);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (9, 'bankcard', 'Indonesia', 10, null, null);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (10, 'jcb', 'South Africa', 6, 19, 37);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (11, 'jcb', 'China', 9, 10, 21);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (12, 'mastercard', 'Norway', 7, 14, 38);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (13, 'jcb', 'Indonesia', 11, 16, 27);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (14, 'bankcard', 'France', 7, 12, 17);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (15, 'jcb', 'Guatemala', 7, 26, 17);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (16, 'jcb', 'France', 3, 19, 30);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (17, 'maestro', 'China', 8, null, null);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (18, 'mastercard', 'Poland', 9, 19, 36);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (19, 'china-unionpay', 'Poland', 6, 36, 36);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (20, 'jcb', 'Israel', 9, 16, 28);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (21, 'instapayment', 'Philippines', 7, 36, 19);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (22, 'diners-club-enroute', 'Brazil', 11, null, null);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (23, 'americanexpress', 'Russia', 11, 17, 22);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (24, 'jcb', 'Indonesia', 10, 40, 34);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (25, 'jcb', 'Ecuador', 7, 33, 17);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (26, 'jcb', 'China', 3, null, null);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (27, 'china-unionpay', 'Sweden', 11, 32, 17);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (28, 'instapayment', 'France', 11, 24, 20);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (29, 'switch', 'Zimbabwe', 9, 32, 34);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (30, 'maestro', 'Albania', 7, 36, 39);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (31, 'mastercard', 'China', 5, null, null);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (32, 'china-unionpay', 'Egypt', 7, 12, 37);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (33, 'mastercard', 'South Africa', 11, 24, 30);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (34, 'mastercard', 'Pakistan', 3, null, null);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (35, 'switch', 'Sweden', 4, null, null);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (36, 'china-unionpay', 'Egypt', 10, 14, 35);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (37, 'jcb', 'Bolivia', 8, 40, 28);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (38, 'visa', 'France', 5, 13, 34);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (39, 'diners-club-enroute', 'China', 9, 33, 15);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (40, 'mastercard', 'China', 3, 20, 21);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (41, 'jcb', 'Indonesia', 7, 36, 29);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (42, 'diners-club-enroute', 'Brazil', 5, 28, 36);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (43, 'instapayment', 'France', 10, 16, 10);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (44, 'solo', 'Papua New Guinea', 11, null, null);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (45, 'switch', 'Georgia', 10, 36, 16);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (46, 'instapayment', 'Czech Republic', 6, 33, 21);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (47, 'china-unionpay', 'Iran', 5, 25, 32);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (48, 'diners-club-us-ca', 'Somalia', 3, 35, 17);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (49, 'jcb', 'Indonesia', 11, 28, 37);
insert into plant_care_profile_default (plantTypeId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (50, 'switch', 'Indonesia', 7, null, null);

insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (1, 'Stringtough', 'Shuitianhe', 34, 35, 32);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (2, 'Duobam', 'Oqtosh', 34, 63, 85);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (3, 'Flowdesk', 'Tanjungampalu', 10, 12, 25);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (4, 'Bytecard', 'Brunflo', 57, 38, 73);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (5, 'Konklux', 'Ouro Sogui', 12, 34, 98);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (6, 'Aerified', 'Bendan', 78, 74, 48);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (7, 'Kanlam', 'Río Colorado', 43, 92, 11);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (8, 'Stronghold', 'Sukaraharja', 12, 66, 100);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (9, 'Zathin', 'Semampir', 42, 96, 27);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (10, 'Voyatouch', 'Novopokrovskaya', 32, 71, 35);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (11, 'Alpha', 'Montpellier', 50, 94, 48);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (12, 'Stringtough', 'Burevestnik', 16, 58, 55);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (13, 'Hatity', 'Delaware', 45, 53, 97);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (14, 'Sub-Ex', 'Komatsu', 60, 67, 38);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (15, 'Andalax', 'Lavradio', 60, 65, 99);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (16, 'Lotstring', 'Bitkine', 55, 82, 17);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (17, 'Veribet', 'Rayside-Balfour', 74, 92, 20);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (18, 'Opela', 'Codó', 19, 31, 57);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (19, 'Temp', 'Seteluk Tengah', 72, 21, 79);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (20, 'Bigtax', 'Wilmington', 44, 66, 8);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (21, 'Alpha', 'Krajan Suco', 43, 95, 77);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (22, 'Treeflex', 'Porto Velho', 78, 71, 48);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (23, 'Bamity', 'Quiaios', 22, 54, 39);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (24, 'Zamit', 'Guaçuí', 42, 11, 60);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (25, 'Opela', 'Piasek', 63, 47, 47);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (26, 'Keylex', 'Cam Lâm', 87, 45, 4);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (27, 'Matsoft', 'Kyriáki', 15, 37, 52);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (28, 'Fix San', 'Klippan', 2, 15, 42);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (29, 'Otcom', 'Bay-ang', 6, 81, 90);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (30, 'Flexidy', 'Naha-shi', 24, 71, 12);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (31, 'It', 'Yuanqiao', 27, 43, 91);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (32, 'Zontrax', 'Pavlohrad', 24, 71, 4);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (33, 'Gembucket', 'Mozzozzin Sur', 91, 59, 15);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (34, 'Gembucket', 'Aoshi', 80, 87, 5);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (35, 'Temp', 'Mawang', 71, 64, 31);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (36, 'Zontrax', 'Haoyi', 77, 66, 46);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (37, 'Fintone', 'Huaishu', 73, 71, 25);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (38, 'Tin', 'Makati City', 13, 72, 57);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (39, 'Flowdesk', 'Nago', 96, 28, 44);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (40, 'Zontrax', 'Obertyn', 55, 49, 88);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (41, 'Sonsing', 'Xingzhen', 36, 52, 83);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (42, 'Konklab', 'Limassol', 55, 82, 7);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (43, 'Y-find', 'Binitinan', 88, 38, 96);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (44, 'Kanlam', 'Xiapu', 94, 77, 1);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (45, 'Zontrax', 'Örnsköldsvik', 83, 12, 93);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (46, 'Bitchip', 'Stockholm', 24, 27, 18);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (47, 'Overhold', 'Palykavichy Pyershyya', 67, 82, 18);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (48, 'Vagram', 'Santa Adélia', 43, 27, 24);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (49, 'Greenlam', 'Mazha', 30, 87, 3);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (50, 'Tempsoft', 'Kafarati', 82, 91, 68);

insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Gun', 'Renal autotransplant', 12, 17);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Connie', 'Contrast x-ray of orbit', 13, 3);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Benito', 'Bilat subq mammectom NEC', 5, 30);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Dev', 'Opn fx red w int fix NEC', 22, 8);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Malva', 'Vaginal repair NEC', 20, 9);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Jeanine', 'Extraoc musc dx proc NEC', 30, 30);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Christa', 'Pulmon art wedge monitor', 2, 19);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Arin', 'Other skin & subq i & d', 27, 19);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Isadore', 'Replac m/s immob dev NEC', 27, 24);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Torr', 'Tenotomy of hand', 28, 24);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Madonna', 'Removal trunk FB NEC', 12, 10);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Gilli', 'Removal vulvar FB', 8, 25);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Guillema', 'Opn bx larynx or trachea', 21, 10);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Malchy', 'Masters'' 2-step test', 5, 28);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Kerwin', 'Open seminal vesicles bx', 5, 7);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Cynthea', 'Refus lmb/lmbsc ant/post', 11, 14);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Barrie', 'Fit below knee prosthes', 19, 23);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Hew', 'Endosc remove panc stone', 24, 5);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Hamel', 'Endovasc embol hd/nk ves', 4, 27);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Francklin', 'Occlude arm vessel NEC', 11, 4);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Gerhardt', 'Sympath nerve division', 9, 16);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Michele', 'Urethral reanastomosis', 25, 25);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Renado', 'Thoracic vessel inc NEC', 22, 29);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Nonna', 'Bact smear NOS', 28, 1);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Tomasina', 'Lap unilat oophorectomy', 14, 24);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Stella', 'Lt heart angiocardiogram', 21, 1);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Haleigh', 'Leg varicos v liga-strip', 26, 10);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Northrup', 'Transplant spermat cord', 16, 10);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Ellen', 'Late repair per nerv inj', 21, 19);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Georgette', 'Radioisot teleradiother', 29, 28);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Charline', 'Manual reduc rect prolap', 19, 20);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Jone', 'Type 4 tympanoplasty', 27, 17);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Babette', 'Injection into marrow', 27, 27);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Grantley', 'Appl ext fix dev-patella', 27, 5);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Belle', 'Suture kidney laceration', 6, 14);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Mariette', 'Cell block/pap-ent/laryn', 22, 25);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Casar', 'Percutan renal aspirat', 9, 22);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Shane', 'Total patellectomy', 23, 3);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Sheilah', 'Ind therap psychsex dysf', 1, 5);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Byram', 'Wide exc bony palate les', 3, 27);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Tiebout', 'Nasal sinus fistula clos', 17, 13);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Thornie', 'Close appendiceal fistul', 13, 26);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Cosmo', 'Endoscop dilate pylorus', 21, 6);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Cirstoforo', 'Transfer of finger', 20, 16);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Chrissie', 'Skin excision for graft', 5, 12);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Minor', 'Partial nephrectomy', 4, 27);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Arabel', 'Thorac esophagogastrost', 13, 22);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Elvin', 'Lap abdperneal resc rec', 5, 1);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Jay', 'Relaxation of scar', 22, 5);
insert into plants (plantName, plantDesc, plantTypeId, userId) values ('Emmey', 'Parasitology-op wound', 8, 19);

insert into tags (label) values ('African snake (unidentified)');
insert into tags (label) values ('European beaver');
insert into tags (label) values ('Brown lemur');
insert into tags (label) values ('Alligator, american');
insert into tags (label) values ('Squirrel, nelson ground');
insert into tags (label) values ('Agile wallaby');
insert into tags (label) values ('South African hedgehog');
insert into tags (label) values ('Snow goose');
insert into tags (label) values ('Black-crowned crane');
insert into tags (label) values ('Rhinoceros, black');
insert into tags (label) values ('Madagascar hawk owl');
insert into tags (label) values ('Goose, snow');
insert into tags (label) values ('Cat, ringtail');
insert into tags (label) values ('Squirrel, nelson ground');
insert into tags (label) values ('Ibis, sacred');
insert into tags (label) values ('Striated heron');
insert into tags (label) values ('Hippopotamus');
insert into tags (label) values ('Weaver, sociable');
insert into tags (label) values ('Openbill stork');
insert into tags (label) values ('Gull, kelp');
insert into tags (label) values ('Dolphin, striped');
insert into tags (label) values ('Brush-tailed rat kangaroo');
insert into tags (label) values ('Bent-toed gecko');
insert into tags (label) values ('Spotted deer');
insert into tags (label) values ('Openbill stork');
insert into tags (label) values ('Klipspringer');
insert into tags (label) values ('Gull, southern black-backed');
insert into tags (label) values ('Langur, gray');
insert into tags (label) values ('Langur, common');
insert into tags (label) values ('Kangaroo, jungle');
insert into tags (label) values ('Denham''s bustard');
insert into tags (label) values ('Alligator, american');
insert into tags (label) values ('Squirrel glider');
insert into tags (label) values ('Red-billed hornbill');
insert into tags (label) values ('Beisa oryx');
insert into tags (label) values ('Meerkat, red');
insert into tags (label) values ('Kelp gull');
insert into tags (label) values ('Bontebok');
insert into tags (label) values ('Pale-throated three-toed sloth');
insert into tags (label) values ('Blue-footed booby');
insert into tags (label) values ('Brush-tailed bettong');
insert into tags (label) values ('Yellow mongoose');
insert into tags (label) values ('Boa, emerald green tree');
insert into tags (label) values ('Deer, barasingha');
insert into tags (label) values ('Tortoise, burmese black mountain');
insert into tags (label) values ('Parrot, hawk-headed');
insert into tags (label) values ('Black-winged stilt');
insert into tags (label) values ('Trumpeter, green-winged');
insert into tags (label) values ('Savannah deer (unidentified)');
insert into tags (label) values ('Painted stork');

insert into plant_tags (plantTypeId, tagId) values (14, 14);
insert into plant_tags (plantTypeId, tagId) values (10, 42);
insert into plant_tags (plantTypeId, tagId) values (18, 49);
insert into plant_tags (plantTypeId, tagId) values (3, 39);
insert into plant_tags (plantTypeId, tagId) values (37, 24);
insert into plant_tags (plantTypeId, tagId) values (46, 35);
insert into plant_tags (plantTypeId, tagId) values (21, 24);
insert into plant_tags (plantTypeId, tagId) values (38, 31);
insert into plant_tags (plantTypeId, tagId) values (17, 13);
insert into plant_tags (plantTypeId, tagId) values (12, 43);
insert into plant_tags (plantTypeId, tagId) values (36, 1);
insert into plant_tags (plantTypeId, tagId) values (43, 26);
insert into plant_tags (plantTypeId, tagId) values (37, 41);
insert into plant_tags (plantTypeId, tagId) values (47, 2);
insert into plant_tags (plantTypeId, tagId) values (47, 1);
insert into plant_tags (plantTypeId, tagId) values (37, 14);
insert into plant_tags (plantTypeId, tagId) values (49, 35);
insert into plant_tags (plantTypeId, tagId) values (1, 5);
insert into plant_tags (plantTypeId, tagId) values (36, 29);
insert into plant_tags (plantTypeId, tagId) values (2, 40);
insert into plant_tags (plantTypeId, tagId) values (5, 11);
insert into plant_tags (plantTypeId, tagId) values (34, 46);
insert into plant_tags (plantTypeId, tagId) values (32, 4);
insert into plant_tags (plantTypeId, tagId) values (16, 22);
insert into plant_tags (plantTypeId, tagId) values (2, 37);
insert into plant_tags (plantTypeId, tagId) values (14, 28);
insert into plant_tags (plantTypeId, tagId) values (46, 27);
insert into plant_tags (plantTypeId, tagId) values (44, 36);
insert into plant_tags (plantTypeId, tagId) values (27, 15);
insert into plant_tags (plantTypeId, tagId) values (45, 15);
insert into plant_tags (plantTypeId, tagId) values (40, 41);
insert into plant_tags (plantTypeId, tagId) values (17, 24);
insert into plant_tags (plantTypeId, tagId) values (36, 43);
insert into plant_tags (plantTypeId, tagId) values (40, 29);
insert into plant_tags (plantTypeId, tagId) values (5, 3);
insert into plant_tags (plantTypeId, tagId) values (14, 17);
insert into plant_tags (plantTypeId, tagId) values (15, 38);
insert into plant_tags (plantTypeId, tagId) values (23, 34);
insert into plant_tags (plantTypeId, tagId) values (23, 22);
insert into plant_tags (plantTypeId, tagId) values (28, 38);
insert into plant_tags (plantTypeId, tagId) values (23, 1);
insert into plant_tags (plantTypeId, tagId) values (48, 24);
insert into plant_tags (plantTypeId, tagId) values (4, 37);
insert into plant_tags (plantTypeId, tagId) values (39, 45);
insert into plant_tags (plantTypeId, tagId) values (37, 18);
insert into plant_tags (plantTypeId, tagId) values (11, 33);
insert into plant_tags (plantTypeId, tagId) values (32, 25);
insert into plant_tags (plantTypeId, tagId) values (34, 16);
insert into plant_tags (plantTypeId, tagId) values (24, 20);
insert into plant_tags (plantTypeId, tagId) values (48, 28);