CREATE TABLE `users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  `bio` VARCHAR(255) NULL,
  `startDate` DATETIME NOT NULL,
  `reputation` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE);

  -- CREATE TABLE movies(title VARCHAR(50) NOT NULL,genre VARCHAR(30) NOT NULL,director VARCHAR(60) NOT NULL,release_year INT NOT NULL,PRIMARY KEY(title));

-- CREATE TABLE `users`(`id` INT NOT NULL AUTO_INCREMENT,`username` VARCHAR(255) NOT NULL,`email` VARCHAR(64) NOT NULL,`bio` VARCHAR(255) NULL,`startDate` DATETIME NOT NULL,`reputation` INT NOT NULL DEFAULT 0,PRIMARY KEY (`id`),UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE);