insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (1, 'Stringtough', 'Shuitianhe', 34, 35, 32);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (2, 'Duobam', 'Oqtosh', 34, 63, 85);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (3, 'Flowdesk', 'Tanjungampalu', 10, 12, 25);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (4, 'Bytecard', 'Brunflo', 57, 38, 73);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (5, 'Konklux', 'Ouro Sogui', 12, 34, 98);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (6, 'Aerified', 'Bendan', 78, 74, 48);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (7, 'Kanlam', 'Río Colorado', 43, 92, 11);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (8, 'Stronghold', 'Sukaraharja', 12, 66, 100);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (9, 'Zathin', 'Semampir', 42, 96, 27);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (10, 'Voyatouch', 'Novopokrovskaya', 32, 71, 35);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (11, 'Alpha', 'Montpellier', 50, 94, 48);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (12, 'Stringtough', 'Burevestnik', 16, 58, 55);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (13, 'Hatity', 'Delaware', 45, 53, 97);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (14, 'Sub-Ex', 'Komatsu', 60, 67, 38);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (15, 'Andalax', 'Lavradio', 60, 65, 99);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (16, 'Lotstring', 'Bitkine', 55, 82, 17);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (17, 'Veribet', 'Rayside-Balfour', 74, 92, 20);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (18, 'Opela', 'Codó', 19, 31, 57);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (19, 'Temp', 'Seteluk Tengah', 72, 21, 79);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (20, 'Bigtax', 'Wilmington', 44, 66, 8);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (21, 'Alpha', 'Krajan Suco', 43, 95, 77);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (22, 'Treeflex', 'Porto Velho', 78, 71, 48);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (23, 'Bamity', 'Quiaios', 22, 54, 39);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (24, 'Zamit', 'Guaçuí', 42, 11, 60);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (25, 'Opela', 'Piasek', 63, 47, 47);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (26, 'Keylex', 'Cam Lâm', 87, 45, 4);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (27, 'Matsoft', 'Kyriáki', 15, 37, 52);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (28, 'Fix San', 'Klippan', 2, 15, 42);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (29, 'Otcom', 'Bay-ang', 6, 81, 90);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (30, 'Flexidy', 'Naha-shi', 24, 71, 12);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (31, 'It', 'Yuanqiao', 27, 43, 91);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (32, 'Zontrax', 'Pavlohrad', 24, 71, 4);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (33, 'Gembucket', 'Mozzozzin Sur', 91, 59, 15);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (34, 'Gembucket', 'Aoshi', 80, 87, 5);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (35, 'Temp', 'Mawang', 71, 64, 31);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (36, 'Zontrax', 'Haoyi', 77, 66, 46);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (37, 'Fintone', 'Huaishu', 73, 71, 25);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (38, 'Tin', 'Makati City', 13, 72, 57);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (39, 'Flowdesk', 'Nago', 96, 28, 44);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (40, 'Zontrax', 'Obertyn', 55, 49, 88);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (41, 'Sonsing', 'Xingzhen', 36, 52, 83);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (42, 'Konklab', 'Limassol', 55, 82, 7);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (43, 'Y-find', 'Binitinan', 88, 38, 96);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (44, 'Kanlam', 'Xiapu', 94, 77, 1);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (45, 'Zontrax', 'Örnsköldsvik', 83, 12, 93);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (46, 'Bitchip', 'Stockholm', 24, 27, 18);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (47, 'Overhold', 'Palykavichy Pyershyya', 67, 82, 18);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (48, 'Vagram', 'Santa Adélia', 43, 27, 24);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (49, 'Greenlam', 'Mazha', 30, 87, 3);
insert into plant_care_profile (plantId, soilType, plantLocation, daysBetweenWatering, daysBetweenRepotting, daysBetweenFertilizer) values (50, 'Tempsoft', 'Kafarati', 82, 91, 68);