insert into plant_types (type, commonName, fullName) values ('Vinyl', 'Showy Gilia', 'Gilia cana (M.E. Jones) A. Heller ssp. triceps (Brand) A.D. Grant & V.E. Grant');
insert into plant_types (type, commonName, fullName) values ('Vinyl', 'Hound''s Tongue', 'Cynoglossum L.');
insert into plant_types (type, commonName, fullName) values ('Glass', 'Graham''s Ticktrefoil', 'Desmodium grahamii A. Gray');
insert into plant_types (type, commonName, fullName) values ('Brass', 'Western Mountain Ash', 'Sorbus sitchensis M. Roem.');
insert into plant_types (type, commonName, fullName) values ('Wood', 'Calathea', 'Calathea G. Mey.');
insert into plant_types (type, commonName, fullName) values ('Rubber', 'Summer Farewell', 'Dalea pinnata (J.F. Gmel.) Barneby');
insert into plant_types (type, commonName, fullName) values ('Rubber', 'Cascara Buckthorn', 'Frangula purshiana (DC.) A. Gray');
insert into plant_types (type, commonName, fullName) values ('Glass', 'Erect Seaberry', 'Haloragis erecta (Murray) Eichler');
insert into plant_types (type, commonName, fullName) values ('Plastic', 'Jones'' Lupine', 'Lupinus jonesii Rydb.');
insert into plant_types (type, commonName, fullName) values ('Glass', 'Japanese Torreya', 'Torreya nucifera (L.) Siebold & Zucc.');
insert into plant_types (type, commonName, fullName) values ('Steel', 'Tortured Horsehair Lichen', 'Bryoria tortuosa (G. Merr.) Brodo & D. Hawksw.');
insert into plant_types (type, commonName, fullName) values ('Steel', 'Cyrto-hypnum Moss', 'Cyrto-hypnum involvens (Hedw.) W.R. Buck & H.A. Crum');
insert into plant_types (type, commonName, fullName) values ('Vinyl', 'Purplestem Aster', 'Symphyotrichum puniceum (L.) Á. Löve & D. Löve var. scabricaule (Shinners) G.L. Nesom');
insert into plant_types (type, commonName, fullName) values ('Granite', 'Fragile Leaf Dicranum Moss', 'Dicranum fragilifolium Lindb.');
insert into plant_types (type, commonName, fullName) values ('Brass', 'Raiche''s Clarkia', 'Clarkia concinna (Fisch. & C.A. Mey.) Greene ssp. raichei G. Allen, V. Ford & L. Gottlieb');
insert into plant_types (type, commonName, fullName) values ('Steel', 'Remy''s Sandmat', 'Chamaesyce remyi (A. Gray ex Boiss.) Croizat & O. Deg. var. kauaiensis (O. Deg. & Sherff) O. Deg. & I. Deg.');
insert into plant_types (type, commonName, fullName) values ('Brass', 'Linearleaf Snapdragon', 'Misopates orontium (L.) Raf.');
insert into plant_types (type, commonName, fullName) values ('Plexiglass', 'Tundra Shootingstar', 'Dodecatheon austrofrigidum K.L. Chambers');
insert into plant_types (type, commonName, fullName) values ('Plexiglass', 'Rim Lichen', 'Lecanora orae-frigidae R. Sant.');
insert into plant_types (type, commonName, fullName) values ('Steel', 'Wright''s Cudweed', 'Pseudognaphalium canescens (DC.) W.A. Weber ssp. microcephalum (Nutt.) Kartesz');
insert into plant_types (type, commonName, fullName) values ('Aluminum', 'Rough Stoneseed', 'Lithospermum matamorense DC.');
insert into plant_types (type, commonName, fullName) values ('Brass', 'Tracy''s Beaksedge', 'Rhynchospora tracyi Britton');
insert into plant_types (type, commonName, fullName) values ('Stone', 'False Rue Anemone', 'Enemion Raf.');
insert into plant_types (type, commonName, fullName) values ('Steel', 'Urban''s Flatsedge', 'Cyperus urbanii Boeckeler');
insert into plant_types (type, commonName, fullName) values ('Wood', 'Limestone Milkvetch', 'Astragalus titanophilus Barneby');
insert into plant_types (type, commonName, fullName) values ('Vinyl', 'Tall Townsend Daisy', 'Townsendia eximia A. Gray');
insert into plant_types (type, commonName, fullName) values ('Stone', 'Resinous Maiden Fern', 'Thelypteris resinifera (Desv.) Proctor');
insert into plant_types (type, commonName, fullName) values ('Steel', 'Strict Primrose', 'Primula stricta Hornem.');
insert into plant_types (type, commonName, fullName) values ('Granite', 'White Dammar', 'Vateria indica L.');
insert into plant_types (type, commonName, fullName) values ('Vinyl', 'Spotted Beebalm', 'Monarda punctata L. ssp. punctata var. intermedia (E.M. McClint. & Epling) Waterf.');
insert into plant_types (type, commonName, fullName) values ('Steel', 'Stiff Star-grass', 'Hypoxis rigida Chapm.');
insert into plant_types (type, commonName, fullName) values ('Granite', 'Rusty Swordfern', 'Polystichum echinatum (J.F. Gmel.) C. Chr.');
insert into plant_types (type, commonName, fullName) values ('Steel', 'Hall''s Fissidens Moss', 'Fissidens hallii Austin');
insert into plant_types (type, commonName, fullName) values ('Brass', 'Neckeropsis Moss', 'Neckeropsis Reichardt');
insert into plant_types (type, commonName, fullName) values ('Plastic', 'Cacao', 'Theobroma cacao L.');
insert into plant_types (type, commonName, fullName) values ('Plastic', 'Langsdorf''s Lousewort', 'Pedicularis langsdorffii Fisch. ex Stev.');
insert into plant_types (type, commonName, fullName) values ('Steel', 'Acid-loving Sedge', 'Carex acidicola Naczi');
insert into plant_types (type, commonName, fullName) values ('Glass', 'Woodland Rush', 'Juncus subcaudatus (Engelm.) Coville & S.F. Blake');
insert into plant_types (type, commonName, fullName) values ('Wood', 'Parmotrema Lichen', 'Parmotrema xanthinum (Müll. Arg.) Hale');
insert into plant_types (type, commonName, fullName) values ('Stone', 'Western False Asphodel', 'Triantha occidentalis (S. Watson) Gates');
insert into plant_types (type, commonName, fullName) values ('Plastic', 'Virginia Strawberry', 'Fragaria virginiana Duchesne ssp. virginiana');
insert into plant_types (type, commonName, fullName) values ('Vinyl', 'Paradox Spilonema Lichen', 'Spilonema paradoxum Bornet');
insert into plant_types (type, commonName, fullName) values ('Plastic', 'Purple Coneflower', 'Echinacea Moench');
insert into plant_types (type, commonName, fullName) values ('Granite', 'Alsike Clover', 'Trifolium hybridum L.');
insert into plant_types (type, commonName, fullName) values ('Wood', 'Geysers Panicgrass', 'Dichanthelium acuminatum (Sw.) Gould & C.A. Clark var. thermale (Bol.) Freckmann');
insert into plant_types (type, commonName, fullName) values ('Steel', 'Sulphur-flower Buckwheat', 'Eriogonum umbellatum Torr. var. furcosum Reveal');
insert into plant_types (type, commonName, fullName) values ('Plexiglass', 'Golden Princesplume', 'Stanleya pinnata (Pursh) Britton var. integrifolia (James ex Torr.) Rollins');
insert into plant_types (type, commonName, fullName) values ('Stone', 'Fairyduster', 'Calliandra eriophylla Benth.');
insert into plant_types (type, commonName, fullName) values ('Rubber', 'Hairy Yellow Vetch', 'Vicia hybrida L.');
insert into plant_types (type, commonName, fullName) values ('Brass', 'Hamatocaulis Moss', 'Hamatocaulis vernicosus (Mitt.) Hedenäs');