insert into plants (name, description, plantTypeId, userId) values ('Gun', 'Renal autotransplant', 12, 17);
insert into plants (name, description, plantTypeId, userId) values ('Connie', 'Contrast x-ray of orbit', 13, 3);
insert into plants (name, description, plantTypeId, userId) values ('Benito', 'Bilat subq mammectom NEC', 5, 30);
insert into plants (name, description, plantTypeId, userId) values ('Dev', 'Opn fx red w int fix NEC', 22, 8);
insert into plants (name, description, plantTypeId, userId) values ('Malva', 'Vaginal repair NEC', 20, 9);
insert into plants (name, description, plantTypeId, userId) values ('Jeanine', 'Extraoc musc dx proc NEC', 30, 30);
insert into plants (name, description, plantTypeId, userId) values ('Christa', 'Pulmon art wedge monitor', 2, 19);
insert into plants (name, description, plantTypeId, userId) values ('Arin', 'Other skin & subq i & d', 27, 19);
insert into plants (name, description, plantTypeId, userId) values ('Isadore', 'Replac m/s immob dev NEC', 27, 24);
insert into plants (name, description, plantTypeId, userId) values ('Torr', 'Tenotomy of hand', 28, 24);
insert into plants (name, description, plantTypeId, userId) values ('Madonna', 'Removal trunk FB NEC', 12, 10);
insert into plants (name, description, plantTypeId, userId) values ('Gilli', 'Removal vulvar FB', 8, 25);
insert into plants (name, description, plantTypeId, userId) values ('Guillema', 'Opn bx larynx or trachea', 21, 10);
insert into plants (name, description, plantTypeId, userId) values ('Malchy', 'Masters'' 2-step test', 5, 28);
insert into plants (name, description, plantTypeId, userId) values ('Kerwin', 'Open seminal vesicles bx', 5, 7);
insert into plants (name, description, plantTypeId, userId) values ('Cynthea', 'Refus lmb/lmbsc ant/post', 11, 14);
insert into plants (name, description, plantTypeId, userId) values ('Barrie', 'Fit below knee prosthes', 19, 23);
insert into plants (name, description, plantTypeId, userId) values ('Hew', 'Endosc remove panc stone', 24, 5);
insert into plants (name, description, plantTypeId, userId) values ('Hamel', 'Endovasc embol hd/nk ves', 4, 27);
insert into plants (name, description, plantTypeId, userId) values ('Francklin', 'Occlude arm vessel NEC', 11, 4);
insert into plants (name, description, plantTypeId, userId) values ('Gerhardt', 'Sympath nerve division', 9, 16);
insert into plants (name, description, plantTypeId, userId) values ('Michele', 'Urethral reanastomosis', 25, 25);
insert into plants (name, description, plantTypeId, userId) values ('Renado', 'Thoracic vessel inc NEC', 22, 29);
insert into plants (name, description, plantTypeId, userId) values ('Nonna', 'Bact smear NOS', 28, 1);
insert into plants (name, description, plantTypeId, userId) values ('Tomasina', 'Lap unilat oophorectomy', 14, 24);
insert into plants (name, description, plantTypeId, userId) values ('Stella', 'Lt heart angiocardiogram', 21, 1);
insert into plants (name, description, plantTypeId, userId) values ('Haleigh', 'Leg varicos v liga-strip', 26, 10);
insert into plants (name, description, plantTypeId, userId) values ('Northrup', 'Transplant spermat cord', 16, 10);
insert into plants (name, description, plantTypeId, userId) values ('Ellen', 'Late repair per nerv inj', 21, 19);
insert into plants (name, description, plantTypeId, userId) values ('Georgette', 'Radioisot teleradiother', 29, 28);
insert into plants (name, description, plantTypeId, userId) values ('Charline', 'Manual reduc rect prolap', 19, 20);
insert into plants (name, description, plantTypeId, userId) values ('Jone', 'Type 4 tympanoplasty', 27, 17);
insert into plants (name, description, plantTypeId, userId) values ('Babette', 'Injection into marrow', 27, 27);
insert into plants (name, description, plantTypeId, userId) values ('Grantley', 'Appl ext fix dev-patella', 27, 5);
insert into plants (name, description, plantTypeId, userId) values ('Belle', 'Suture kidney laceration', 6, 14);
insert into plants (name, description, plantTypeId, userId) values ('Mariette', 'Cell block/pap-ent/laryn', 22, 25);
insert into plants (name, description, plantTypeId, userId) values ('Casar', 'Percutan renal aspirat', 9, 22);
insert into plants (name, description, plantTypeId, userId) values ('Shane', 'Total patellectomy', 23, 3);
insert into plants (name, description, plantTypeId, userId) values ('Sheilah', 'Ind therap psychsex dysf', 1, 5);
insert into plants (name, description, plantTypeId, userId) values ('Byram', 'Wide exc bony palate les', 3, 27);
insert into plants (name, description, plantTypeId, userId) values ('Tiebout', 'Nasal sinus fistula clos', 17, 13);
insert into plants (name, description, plantTypeId, userId) values ('Thornie', 'Close appendiceal fistul', 13, 26);
insert into plants (name, description, plantTypeId, userId) values ('Cosmo', 'Endoscop dilate pylorus', 21, 6);
insert into plants (name, description, plantTypeId, userId) values ('Cirstoforo', 'Transfer of finger', 20, 16);
insert into plants (name, description, plantTypeId, userId) values ('Chrissie', 'Skin excision for graft', 5, 12);
insert into plants (name, description, plantTypeId, userId) values ('Minor', 'Partial nephrectomy', 4, 27);
insert into plants (name, description, plantTypeId, userId) values ('Arabel', 'Thorac esophagogastrost', 13, 22);
insert into plants (name, description, plantTypeId, userId) values ('Elvin', 'Lap abdperneal resc rec', 5, 1);
insert into plants (name, description, plantTypeId, userId) values ('Jay', 'Relaxation of scar', 22, 5);
insert into plants (name, description, plantTypeId, userId) values ('Emmey', 'Parasitology-op wound', 8, 19);