insert into tags (label) values ('African snake (unidentified)');
insert into tags (label) values ('European beaver');
insert into tags (label) values ('Brown lemur');
insert into tags (label) values ('Alligator, american');
insert into tags (label) values ('Squirrel, nelson ground');
insert into tags (label) values ('Agile wallaby');
insert into tags (label) values ('South African hedgehog');
insert into tags (label) values ('Snow goose');
insert into tags (label) values ('Black-crowned crane');
insert into tags (label) values ('Rhinoceros, black');
insert into tags (label) values ('Madagascar hawk owl');
insert into tags (label) values ('Goose, snow');
insert into tags (label) values ('Cat, ringtail');
insert into tags (label) values ('Squirrel, nelson ground');
insert into tags (label) values ('Ibis, sacred');
insert into tags (label) values ('Striated heron');
insert into tags (label) values ('Hippopotamus');
insert into tags (label) values ('Weaver, sociable');
insert into tags (label) values ('Openbill stork');
insert into tags (label) values ('Gull, kelp');
insert into tags (label) values ('Dolphin, striped');
insert into tags (label) values ('Brush-tailed rat kangaroo');
insert into tags (label) values ('Bent-toed gecko');
insert into tags (label) values ('Spotted deer');
insert into tags (label) values ('Openbill stork');
insert into tags (label) values ('Klipspringer');
insert into tags (label) values ('Gull, southern black-backed');
insert into tags (label) values ('Langur, gray');
insert into tags (label) values ('Langur, common');
insert into tags (label) values ('Kangaroo, jungle');
insert into tags (label) values ('Denham''s bustard');
insert into tags (label) values ('Alligator, american');
insert into tags (label) values ('Squirrel glider');
insert into tags (label) values ('Red-billed hornbill');
insert into tags (label) values ('Beisa oryx');
insert into tags (label) values ('Meerkat, red');
insert into tags (label) values ('Kelp gull');
insert into tags (label) values ('Bontebok');
insert into tags (label) values ('Pale-throated three-toed sloth');
insert into tags (label) values ('Blue-footed booby');
insert into tags (label) values ('Brush-tailed bettong');
insert into tags (label) values ('Yellow mongoose');
insert into tags (label) values ('Boa, emerald green tree');
insert into tags (label) values ('Deer, barasingha');
insert into tags (label) values ('Tortoise, burmese black mountain');
insert into tags (label) values ('Parrot, hawk-headed');
insert into tags (label) values ('Black-winged stilt');
insert into tags (label) values ('Trumpeter, green-winged');
insert into tags (label) values ('Savannah deer (unidentified)');
insert into tags (label) values ('Painted stork');