insert into users (username, email, bio, startDate, reputation) values ('ldoog0', 'wivy0@irs.gov', 'Corrosion of second degree of unsp toe(s) (nail), init', '2022-08-26 15:22:50', 0);
insert into users (username, email, bio, startDate, reputation) values ('afitchew1', 'edearlove1@hugedomains.com', 'Traum rupture of ligmt of l little finger at MCP/IP jt, init', '2021-10-19 04:24:53', 0);
insert into users (username, email, bio, startDate, reputation) values ('lmaddock2', 'omcnerlin2@livejournal.com', 'Other specified joint disorders, unspecified hand', '2021-11-01 11:09:32', 0);
insert into users (username, email, bio, startDate, reputation) values ('bcrew3', 'gdore3@wikispaces.com', 'Delayed puberty', '2021-11-08 00:33:03', 0);
insert into users (username, email, bio, startDate, reputation) values ('cbellfield4', 'sgurko4@telegraph.co.uk', 'Retained placenta without hemorrhage', '2022-07-23 18:39:19', 0);
insert into users (username, email, bio, startDate, reputation) values ('bstileman5', 'rcamois5@baidu.com', 'Hirsutism', '2022-01-05 11:05:17', 0);
insert into users (username, email, bio, startDate, reputation) values ('rdubarry6', 'akief6@ow.ly', 'Other infantile and juvenile cataract', '2022-05-25 07:50:52', 0);
insert into users (username, email, bio, startDate, reputation) values ('mlister7', 'wcotterell7@yahoo.co.jp', 'Person outside bus injured in clsn w pedl cyc in traf, subs', '2022-05-30 18:30:53', 0);
insert into users (username, email, bio, startDate, reputation) values ('gwellstead8', 'alocke8@google.co.uk', 'Amebic nondysenteric colitis', '2022-02-06 00:49:45', 0);
insert into users (username, email, bio, startDate, reputation) values ('bmccully9', 'acanelas9@discuz.net', 'Other displaced fracture of lower end of unspecified humerus', '2022-04-21 02:44:02', 0);
insert into users (username, email, bio, startDate, reputation) values ('bsassera', 'cbernakiewicza@artisteer.com', 'Congenital posterior urethral valves', '2022-02-23 13:20:03', 0);
insert into users (username, email, bio, startDate, reputation) values ('dgirodiasb', 'pwatfordb@wordpress.org', 'Fx unsp tarsal bone(s) of unsp ft, subs for fx w routn heal', '2022-06-12 04:12:18', 0);
insert into users (username, email, bio, startDate, reputation) values ('astenningsc', 'asimanekc@wp.com', 'Puncture wound with foreign body of anus, initial encounter', '2022-01-29 22:22:25', 0);
insert into users (username, email, bio, startDate, reputation) values ('epanyerd', 'nemanuellid@huffingtonpost.com', 'ABO incompatibility w delayed hemolytic transfs react, subs', '2021-11-01 17:45:40', 0);
insert into users (username, email, bio, startDate, reputation) values ('acovielloe', 'bvanhesterene@networksolutions.com', 'Contact with other specified machinery, subsequent encounter', '2021-12-22 11:12:57', 0);
insert into users (username, email, bio, startDate, reputation) values ('rdoddemeedef', 'mwinningf@washingtonpost.com', 'Sprain of unspecified cruciate ligament of knee', '2022-07-12 03:46:12', 0);
insert into users (username, email, bio, startDate, reputation) values ('barong', 'efakeg@hao123.com', 'Subluxation of radiocarpal joint of unspecified wrist', '2021-10-18 11:10:06', 0);
insert into users (username, email, bio, startDate, reputation) values ('pshaperoh', 'rgierckh@smh.com.au', 'Insect bite (nonvenomous), unspecified foot, sequela', '2022-05-30 10:58:53', 0);
insert into users (username, email, bio, startDate, reputation) values ('tlenini', 'gskiltoni@weather.com', 'Oth aplastic anemias and other bone marrow failure syndromes', '2021-12-06 13:02:34', 0);
insert into users (username, email, bio, startDate, reputation) values ('ptaylderj', 'apiotrj@paginegialle.it', 'Hypoplasia of penis', '2021-12-18 18:53:53', 0);
insert into users (username, email, bio, startDate, reputation) values ('jhawardk', 'dmazink@1und1.de', 'Ulcerative colitis, unspecified with other complication', '2021-12-18 18:06:40', 0);
insert into users (username, email, bio, startDate, reputation) values ('cwapplel', 'smcgladel@shinystat.com', 'Corrosion of unspecified degree of upper back, sequela', '2022-02-12 00:48:55', 0);
insert into users (username, email, bio, startDate, reputation) values ('llarkm', 'ycalamm@reverbnation.com', 'Toxic effect of noxious substances eaten as food, assault', '2022-02-08 22:09:04', 0);
insert into users (username, email, bio, startDate, reputation) values ('fhendrichsn', 'dickovitzn@washington.edu', 'Struck by falling object on other unpowered watercraft', '2022-03-30 01:51:11', 0);
insert into users (username, email, bio, startDate, reputation) values ('csimonazzio', 'bcalendaro@shinystat.com', 'Nondisp fx of greater tuberosity of l humer, 7thP', '2022-05-17 21:05:02', 0);
insert into users (username, email, bio, startDate, reputation) values ('vsommervillep', 'bmellingp@about.me', 'Posterior dislocation of unspecified hip', '2022-05-09 19:41:01', 0);
insert into users (username, email, bio, startDate, reputation) values ('leickhoffq', 'ccatleyq@live.com', 'Inj extn/abdr musc/fasc/tend of r thm at forarm lv, sequela', '2021-11-28 02:59:03', 0);
insert into users (username, email, bio, startDate, reputation) values ('icoughlinr', 'ascholefieldr@comsenz.com', 'Subluxation of interphalangeal joint of unsp lesser toe(s)', '2021-08-27 23:01:46', 0);
insert into users (username, email, bio, startDate, reputation) values ('otidgewells', 'cgregolins@google.co.uk', 'Unsp injury of deep palmar arch of left hand, subs encntr', '2021-10-01 04:46:18', 0);
insert into users (username, email, bio, startDate, reputation) values ('bhandst', 'akerleyt@nasa.gov', 'Driver of 3-whl mv injured in clsn w nonmtr vehicle in traf', '2022-02-16 08:00:18', 0);
insert into users (username, email, bio, startDate, reputation) values ('spelleru', 'lcholertonu@blogtalkradio.com', 'Insect bite (nonvenomous), unspecified foot, subs encntr', '2021-12-02 02:19:25', 0);
insert into users (username, email, bio, startDate, reputation) values ('awhitnellv', 'bvinkv@telegraph.co.uk', 'Disp fx of lateral malleolus of unsp fibula, 7thF', '2021-10-22 20:41:53', 0);
insert into users (username, email, bio, startDate, reputation) values ('thairsnapew', 'acheaterw@twitter.com', 'Other nonautoimmune hemolytic anemias', '2022-06-22 10:57:47', 0);
insert into users (username, email, bio, startDate, reputation) values ('sworrellx', 'ngrigoryevx@irs.gov', 'Poisoning by cocaine, undetermined', '2021-12-16 12:50:28', 0);
insert into users (username, email, bio, startDate, reputation) values ('ftregunnay', 'umcgeneayy@ox.ac.uk', 'Oth injuries of left wrist, hand and finger(s), sequela', '2022-07-02 19:24:52', 0);
insert into users (username, email, bio, startDate, reputation) values ('mdinningz', 'eshelleyz@joomla.org', 'Maternal care for chromosomal abnormality in fetus, fetus 1', '2022-04-21 23:24:16', 0);
insert into users (username, email, bio, startDate, reputation) values ('rseaborn10', 'osalkeld10@youtube.com', 'Unsp pedl cyclst inj in clsn w statnry object nontraf, sqla', '2021-10-11 21:47:18', 0);
insert into users (username, email, bio, startDate, reputation) values ('bvance11', 'aatterley11@behance.net', 'Oth psychoactive substance dependence w intoxication, unsp', '2022-04-01 15:03:39', 0);
insert into users (username, email, bio, startDate, reputation) values ('aspurr12', 'ggage12@hatena.ne.jp', 'Nondisplaced bimalleolar fracture of unsp lower leg, sequela', '2022-05-01 12:09:06', 0);
insert into users (username, email, bio, startDate, reputation) values ('adrewitt13', 'kszymanek13@adobe.com', 'Burn first degree of unsp single finger (nail) except thumb', '2021-12-23 10:24:32', 0);
insert into users (username, email, bio, startDate, reputation) values ('ctingly14', 'sheckle14@bandcamp.com', 'Displ spiral fx shaft of r femr, 7thM', '2021-10-16 08:34:35', 0);
insert into users (username, email, bio, startDate, reputation) values ('gshuttell15', 'bwrintmore15@constantcontact.com', 'Pedestrian on foot injured in collision w hv veh nontraf', '2022-03-04 23:40:35', 0);
insert into users (username, email, bio, startDate, reputation) values ('rpinkerton16', 'dprevett16@hexun.com', 'Path fracture in neoplastic disease, l shoulder, init', '2021-09-12 05:47:24', 0);
insert into users (username, email, bio, startDate, reputation) values ('jbussell17', 'edik17@shareasale.com', 'Suprvsn of preg with history of ectopic preg, second tri', '2022-07-16 10:22:55', 0);
insert into users (username, email, bio, startDate, reputation) values ('egonnard18', 'hconfort18@acquirethisname.com', 'Oth retrovirus as the cause of diseases classified elsewhere', '2022-05-16 22:14:05', 0);
insert into users (username, email, bio, startDate, reputation) values ('rfleckney19', 'iplom19@umn.edu', 'Retained (old) fb in iris or ciliary body, bilateral', '2021-09-06 01:55:23', 0);
insert into users (username, email, bio, startDate, reputation) values ('acrome1a', 'gfatscher1a@goo.ne.jp', 'Subluxation of proximal interphaln joint of l idx fngr, subs', '2021-11-12 14:29:53', 0);
insert into users (username, email, bio, startDate, reputation) values ('vhugh1b', 'kplaskitt1b@newyorker.com', 'Other secondary chronic gout, left elbow, with tophus', '2021-11-15 18:59:58', 0);
insert into users (username, email, bio, startDate, reputation) values ('gbaterip1c', 'vgrabert1c@acquirethisname.com', 'Other secondary osteonecrosis, unspecified shoulder', '2022-05-27 01:08:39', 0);
insert into users (username, email, bio, startDate, reputation) values ('wpembery1d', 'redy1d@cdc.gov', 'Sprain of the superior tibiofibul joint and ligament, l knee', '2022-03-26 12:56:27', 0);